### ISSUE TITLE
Preloading fails to handle class/package options properly 

### ISSUE THREAD

**Issue by angerhang** [brucemiller/LaTeXML#687] opened 2015-11-19 21:23 UTC
It is best to show the problem with the following example. We have a `test.tex` which loads a `optionTest.cls` with option `test` and then `optionTest.cls.ltxml` passes the option to `optionTest.sty.ltxml`.
`test.tex`
```tex
\documentclass[test]{optionTest}
\begin{document}
This is a test.
\end{document}
```
`optionTest.cls.ltxml`
```
package LaTeXML::Package::Pool;
use strict;
use LaTeXML::Package;
DeclareOption('test', sub {AssignValue('@test' => 1, 'global');
		      PassOptions('optionTest','sty',ToString(Digest(T_CS('\CurrentOption')))); });
ProcessOptions();
RequirePackage('optionTest');
1;
```
`optionTest.sty.ltxml`
```
package LaTeXML::Package::Pool;
use strict;
use LaTeXML::Package;
DeclareOption('test', sub {AssignValue('@test' => 1, 'global'); });
ProcessOptions();
if(LookupValue('@test')) { warn "Option activated!";}

1;
```
The problem is  if we preload the optionTest class, the option hander won't be activated. 

Here is the output with preloading 
```
MacBook-Pro:smglom yuancalvin$ cat mv/latexml/test.ltxlog 
(Loading profile /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/Profiles/stex-smglom-module.opt... )
(Loading profile /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/Profiles/stex-smglom-module.opt... )

(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/TeX.pool.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/eTeX.pool.ltxml... 0.01 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/pdfTeX.pool.ltxml... 0.01 sec) 0.18 sec)
(Loading /path/to/localmh/ext/sTeX/sty/optionTest.cls.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/optionTest.sty.ltxml... 0.00 sec) 0.01 sec)

latexmls (LaTeXML version 0.8.1 (KWARC fork); revision 9e47fbe)
processing started Thu Nov 19 21:17:02 2015

(Digesting TeX test...
(Processing content /path/to/localmh/MathHub/smglom/mv/source/test.tex...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/LaTeX.pool.ltxml... 0.18 sec) 0.20 sec) 0.21 sec)
(Building...
(Loading compiled schema /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.01 sec). 0.08 sec)
(Rewriting... 0.00 sec)
(Finalizing... 0.00 sec)
Conversion complete: No obvious problems.

(post-processing...
(Scan test.omdoc processing... 0.00 sec)
(CrossRef test.omdoc processing... 0.00 sec)
(XSLT[using /path/to/localmh/ext/sTeX/sty/../xsl/omdocpost.xsl] test.omdoc processing... 0.01 sec)
(Writer test.omdoc processing... 0.00 sec) 0.02 sec)
Post-processing complete: No obvious problems
``` 
@kohlhase should also know about this.

**Comment by dginev** [comment] 2015-11-19 21:27
Ah, so if you preload the package (in daemon mode) without options, and then use it with options in a concrete conversion, the option doesn't get passed?

Should be easy to verify, not sure about difficulty of fixing. Thanks for the report!

**Comment by brucemiller** [comment] 2015-11-20 16:16
On 19/11/2015 16:27, Deyan Ginev wrote:
> Ah, so if you preload the package (in daemon mode) without options, and
> then use it with options in a concrete conversion, the option doesn't
> get passed?

Kinda nasty. Not sure that even the LaTeX mechanism itself is designed
to allow this; Certainly not for classes, but normally when you've already
loaded a package, it doesn't get reloaded --- I assume even if options have
changed.  Is there a provision for it to reprocess the options?

Preloading is kinda outside the model of LaTeX; other than preloaded
formats, but then there are whole other sets of mechanisms to load &
set options.

Hmmm....

**Comment by dginev** [comment] 2015-11-20 19:36
There are multiple workarounds (and I know Michael is already using one), so there shouldn't be much urgency with addressing the issue here. For now these are feasible:
 * Don't preload the package at all, if options will change for each job
 * or preload it with the exact options set

Maybe we can even punt and say these two workarounds are as good as possible, given the latex model for loading packages? Since a package option can trigger arbitrary turing-complete behaviour, there isn't much we can do.

**Comment by kohlhase** [comment] 2015-11-21 10:45
Actually, I quite agree with Deyan, preloading is outside the the realm of LaTeX compatibility. So we are free to define the intended behavior. 

The only way I would know to give semantics to preloading is that the options are part of the preloading process. I.e. ```--preload=[foo]bar.sty.ltxml``` should do just that: preload ```foo.star.ltxml``` with the ```foo``` option set. If you want the freedom to load ```bar.sty.ltxml``` with other options (maybe even changing options), then do not preload  ```foo.sty.ltxml``` at all, since that fixes the options once and for all. 

In our application (sTeX for MathHub.info), we can live very well with this (once we understand why our options handling never seemed to work), in fact the semantics sketched above is exactly what we need (we only need to update the ```stex*.opt``` files with ```[mh]``` in strategic places).  

So I guess what we should really have is a documentation of the options/preloading behavior. in the LaTeXML manual (at least Bruce can tell us to RTFM if this happens again). Feel free to close this once you have documented.

**Comment by kohlhase** [comment] 2015-11-21 11:16
Actually, I have changed my mind (a bit). While we should certainly keep the behavior and  document it, we should also issue a warning or even an "option clash" error (in the way some LaTeX packages do). I.e. if we have ```--preload=[foo]bar.sty.ltxml``` and then come across a ```\usepackage[baz]{bar}```, then we should raise an error saying something like
``` 
Option clash on package bar: it has been preloaded with options [foo]. 
Your options [bar] will have no effect! Read Section 2.3.4 in the LaTeXML documentation. 
```
I think that this will make things sufficiently clear.

**Comment by brucemiller** [comment] 2015-12-05 13:35
Yeah, this makes sense: I'd forgotten that LaTeX gives you that warning (but only when *different* options are requested; cases where there are no options are silently ignored).  I've patched to add an Error in such cases, but there's no attempt to reload the package, or reinvoke the options.  At least it now tells you there's a problem.

**Closed by brucemiller** 2015-12-05 13:35 UTC
Labels: bug, daemon, packages
