### ISSUE TITLE
After \end{thebibliography} latexml starts appendix

### ISSUE THREAD

**Issue by evoludolab** [brucemiller/LaTeXML#976] opened 2018-04-26 22:23 UTC
This results in unexpected and very different results between the output of `latex` and `lateXML`.

As a minimal example, consider the following code:
```
\documentclass{book}
\begin{document}
\chapter{One}
\begin{thebibliography}{1}
\end{thebibliography}
\chapter{Two}
\end{document}
```

`latex` produces the expected file structure with
- chapter 1 One
- Bibliography
- chapter 2 Two

while `lateXML` produces
- chapter 1 One
- Bibliography
- Appendix A Two

This issue seems to be related to previous (closed) issues: #124 and #412 in particular.

Some more background: because `lateXML` currently does not provide bindings for the chapterbib-package I was looking for a workaround to add a section with references at the end of each chapter by `\include`-ing the corresponding bbl-file but unexpectedly ended up with appendices...

**Comment by dginev** [comment] 2018-04-27 03:15
Thanks for the report! We'll look into it.

**Comment by dginev** [comment] 2018-05-03 21:41
Isn't the `\section*{App 1. Stuff}` example addressed by the `garbage in - garbage out` design principle? In the sense that we don't need to guess something is an appendix if the author doesn't indicate that explicitly.

Reminds of my favourite semantics failure in latex, where you mark list items via:

```tex
 \indent $\bullet$ your item here
 \indent $\bullet$ another item here
 ...
```

**Comment by brucemiller** [comment] 2018-05-06 12:16
You're right, at that point we don't really care if it's an appendix or not, but the problem is that the schema doesn't allow sections back there.  And it would also be fine to let the schema be a bit more sloppy, except that latexml relies on the schema (in many cases) to determine whether to open/close elements. So we'd have to predict the side-effects of the sloppiness.

**Comment by dginev** [comment] 2018-05-06 16:33
Sounds wise. Maybe there are two distinct issues to address here. 

First, the per-chapter backmatter feels like a standard-enough technique of latex writers to support in the schema.

Second, the "appendices written as sections" issue may be soft enough for us to address with graceful error handling. Namely, I am thinking you could turn that specific case of a schema error into a warning, still report it, and the automatically convert the wrongly placed section into a correctly placed appendix.

**Comment by brucemiller** [comment] 2018-05-06 17:09
On the last point, we already sorta do that, but the current case is a section (chapter) being incorrectly converted to an appendix.

The chapter-bib issue probably isn't insurmountable, but a bit messy. Basically consider that you're in a chapter and see a bibliography. Is it a bibliography for the current chapter or for the whole book? (ie. do we close the current chapter or not?)  LaTeX would solve this by having `thebibliography` either invoke `\chapter*{\bibname}`, or `\section*{\bibname}`.  We'd have to capture that choice and open/close appropriately, for every class. And of course, allow backmatter in any sectional unit.

There's already somewhat similar code to deal with appendices, at least when you use `\appendix` (in which case eg. `\chapter` gets redefined). Offhand, if we're a bit sloppy about backmatter, eg. allowing more chapters as well as appendices, perhaps there'd be no harm in the corner cases?

Perhaps slightly more daunting for chapter-bib styles is to use the right selection of `\cite's to build each bibliography. The `chapterbib` package separates the bibliographies *not* on actual chapters, but on include files!

**Comment by siegfriedzoetzsche** [comment] 2018-10-17 13:47
As a side note:
There are actual books that have individual bibliographies in individual sections, sometimes multiple bibliographies in the same section, additional chapter bibliographies and all of that numbered or unnumbered. Basically you can expect bibliographies wherever you could expect a section.

Consider the following example
```latex
\documentclass{book}
\usepackage[utf8]{inputenc}
\usepackage[sectionbib,numbers]{natbib}

\begin{document}

\chapter{CHAP 1}

\section{SEC 1.1}

\def\bibsection{\subsection*{Chapter Bibliography}}
\begin{thebibliography}{12}
\bibitem{bib1} Bla
\end{thebibliography}

\section{SEC 1.2}

\def\bibsection{\subsection*{Chapter Bibliography}}
\begin{thebibliography}{12}
\bibitem{bib1} Bla
\end{thebibliography}

\def\bibsection{\section*{Chapter Bibliography}}
\begin{thebibliography}{12}
\bibitem{bib1} Bla
\end{thebibliography}

\chapter{CHAP 2}

\section{SEC 2.1}

\def\bibsection{\subsection{Chapter Bibliography}}
\begin{thebibliography}{12}
\bibitem{bib1} Bla
\end{thebibliography}

\section{SEC 2.2}

\def\bibsection{\subsection{Chapter Bibliography}}
\begin{thebibliography}{12}
\bibitem{bib1} Bla
\end{thebibliography}

\def\bibsection{\section{Chapter Bibliography}}
\begin{thebibliography}{12}
\bibitem{bib1} Bla
\end{thebibliography}

\end{document}
```

Right now this results in
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?latexml class="book"?>
<?latexml package="inputenc" options="utf8"?>
<?latexml package="natbib" options="sectionbib,numbers"?>
<?latexml RelaxNGSchema="LaTeXML"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
  <resource src="LaTeXML.css" type="text/css"/>
  <resource src="ltx-book.css" type="text/css"/>
  <chapter inlist="toc" xml:id="Ch1">
    <tags>
      <tag>Chapter 1</tag>
      <tag role="refnum">1</tag>
      <tag role="typerefnum">Chapter 1</tag>
    </tags>
    <title><tag close=" ">Chapter 1</tag>CHAP 1</title>
    <toctitle><tag close=" ">1</tag>CHAP 1</toctitle>
    <section inlist="toc" xml:id="Ch1.S1">
      <tags>
        <tag>1.1</tag>
        <tag role="refnum">1.1</tag>
        <tag role="typerefnum">§1.1</tag>
      </tags>
      <title><tag close=" ">1.1</tag>SEC 1.1</title>
    </section>
  </chapter>
  <bibliography xml:id="bib">
    <title>Bibliography</title>
    <biblist>
      <bibitem key="bib1" xml:id="bib.bib1">
        <tags>
          <tag role="number">1</tag>
          <tag role="refnum">[1]</tag>
          <tag role="key">bib1</tag>
        </tags>
        <bibblock> Bla
</bibblock>
      </bibitem>
    </biblist>
  </bibliography>
  <section inlist="toc" xml:id="A0.S2">
    <tags>
      <tag>.2</tag>
      <tag role="refnum">.2</tag>
      <tag role="typerefnum">2.§</tag>
    </tags>
    <title><tag close=" ">.2</tag>SEC 1.2</title>
  </section>
  <bibliography xml:id="biba">
    <title>Bibliography</title>
    <biblist>
      <bibitem key="bib1" xml:id="biba.bib2">
        <tags>
          <tag role="number">2</tag>
          <tag role="refnum">[2]</tag>
          <tag role="key">bib1</tag>
        </tags>
        <bibblock> Bla
</bibblock>
      </bibitem>
    </biblist>
  </bibliography>
  <bibliography xml:id="bibb">
    <title>Bibliography</title>
    <biblist>
      <bibitem key="bib1" xml:id="bibb.bib3">
        <tags>
          <tag role="number">3</tag>
          <tag role="refnum">[3]</tag>
          <tag role="key">bib1</tag>
        </tags>
        <bibblock> Bla
</bibblock>
      </bibitem>
    </biblist>
  </bibliography>
  <appendix inlist="toc" xml:id="A1">
    <tags>
      <tag>Appendix A</tag>
      <tag role="refnum">A</tag>
      <tag role="typerefnum">Appendix A</tag>
    </tags>
    <title><tag close=" ">Appendix A</tag>CHAP 2</title>
    <toctitle><tag close=" ">A</tag>CHAP 2</toctitle>
    <section inlist="toc" xml:id="A1.S1">
      <tags>
        <tag>A.1</tag>
        <tag role="refnum">A.1</tag>
        <tag role="typerefnum">§A.1</tag>
      </tags>
      <title><tag close=" ">A.1</tag>SEC 2.1</title>
    </section>
  </appendix>
  <bibliography xml:id="bibc">
    <title>Bibliography</title>
    <biblist>
      <bibitem key="bib1" xml:id="bibc.bib4">
        <tags>
          <tag role="number">4</tag>
          <tag role="refnum">[4]</tag>
          <tag role="key">bib1</tag>
        </tags>
        <bibblock> Bla
</bibblock>
      </bibitem>
    </biblist>
  </bibliography>
  <section inlist="toc" xml:id="A1.S2">
    <tags>
      <tag>A.2</tag>
      <tag role="refnum">A.2</tag>
      <tag role="typerefnum">§A.2</tag>
    </tags>
    <title><tag close=" ">A.2</tag>SEC 2.2</title>
  </section>
  <bibliography xml:id="bibd">
    <title>Bibliography</title>
    <biblist>
      <bibitem key="bib1" xml:id="bibd.bib5">
        <tags>
          <tag role="number">5</tag>
          <tag role="refnum">[5]</tag>
          <tag role="key">bib1</tag>
        </tags>
        <bibblock> Bla
</bibblock>
      </bibitem>
    </biblist>
  </bibliography>
  <bibliography xml:id="bibe">
    <title>Bibliography</title>
    <biblist>
      <bibitem key="bib1" xml:id="bibe.bib6">
        <tags>
          <tag role="number">6</tag>
          <tag role="refnum">[6]</tag>
          <tag role="key">bib1</tag>
        </tags>
        <bibblock> Bla
</bibblock>
      </bibitem>
    </biblist>
  </bibliography>
</document>
```
Some of the problems:
- The first chapter is closed right before the first bibliography
- Each bibitem should have refnum `[1]`
- The second chapter is not an appendix
- The numbered bibsections in chapter 2 are not numbered in the XML output

**Comment by brucemiller** [comment] 2019-05-22 15:34
Two big shifts here: being able to fill-in multiple things like index, glossary, bibliography with different subsets of the material; being able to correctly position multiple instances of them.  I think I got it sorted out, though there may be some glitches that will turn up.  So, now both your curious examples should work, and a better approach all-round is that there are bindings for bibunits and chapterbib.  Hopefully this will work out for your applications.  Thanks for the report!

**Closed by brucemiller** 2019-05-22 15:34 UTC
Labels: bug

**Comment by evoludolab** [comment] 2019-06-07 21:16
Thanks for fixing the issue and especially for adding `chapterbib`! This will allow me to significantly simplify the somewhat sophisticated workflow needed at present to 'manually' generate the reference sections and compiling everything into an ePub.

While working on a new, streamlined workflow, I noticed one small related issue: when running `latexmlpost` with `--splitat=chapter` it generates separate files for each bibliography even if they were declared as sections at the end of each chapter. When putting the different parts together in an ePub this has some undesired consequences for the formatting. Of course this is very minor and there are plenty of ways to stick the right files together again :-)

**Comment by brucemiller** [comment] 2019-06-09 16:33
Ah, yes; split needs to know which level they're at.  I think I've worked out a good scheme to split them correctly (based on parents/sibling; cfbb2831496faccd280f32bac119d1f80b840833)
