### ISSUE TITLE
Bold zeros in math lost during transformation to HTML

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#948] opened 2018-02-07 19:36 UTC
Applies to LaTeXML 0.8.2.
In math fragments, zeros tagged in bold font are lost during transformation to HTML with MathML, that is: XML fragment
` <XMTok font="bold" meaning="0" role="NUMBER">0</XMTok>` gets transformed to
`<mn></mn>`
Other digits appear unaffected. I tested with 1:
`<XMTok font="bold" meaning="1" role="NUMBER">1</XMTok>`
was transformed into
`<mn>𝟏</mn>`.
The same input LaTeX code (from which quoted XML was derived) worked OK in LaTeXML 0.8.1. Is there any way I could fix this problem?

**Comment by dginev** [comment] 2018-02-07 19:38
I think Bruce just fixed this in #926 -- but you would need the latest GitHub version to take advantage of the fix.

Or of course 0.8.3, when we release it.

**Comment by goska** [comment] 2018-02-07 19:50
On brief reading, #926 mentions specifically output to STDOUT, but I was  writing to an HTML file.

**Comment by dginev** [comment] 2018-02-07 20:00
You can give me the exact input that reproduces the problem and I can test if it is still present in the latest master branch.

I can verify that:
```
 latexmlc --preload=amsmath.sty 'literal:$\boldsymbol{0}$' --dest=test.html
```

produces the zero correctly. So it should be fixed.

**Comment by goska** [comment] 2018-02-07 20:05
OK, your test indicates that the problem is indeed fixed in the latest version. Thanks.

**Comment by dginev** [comment] 2018-02-07 20:14
Sure thing! I actually spotted more encoding issues while testing, so your issue was helpful in improving our encoding robustness. PR is at #949 

I will close here, since things seem OK.

**Closed by dginev** 2018-02-07 20:14 UTC
Labels: duplicate
