### ISSUE TITLE
[regression] No more way to generate pmml + LaTeX annotation

### ISSUE THREAD

**Issue by fred-wang** [brucemiller/LaTeXML#613] opened 2015-05-15 12:50 UTC
See the thread on the mailing list http://lists.jacobs-university.de/pipermail/project-latexml/2015-May/002071.html

Basically, in the past presentation MathML + LaTeX annotation was the default. Now, by default only presentation MathML is generated and there is not any option to attach the LaTeX annotation alone.

So I'd suggest to add an option to generate --keeptex so that the user can explicitly request the TeX annotation. (Of course someone will complain that it is yet another new command line option... but it is not worse than a  introducing a regression + behavior change, no?)

**Comment by dginev** [comment] 2015-05-15 13:02
The regression + behaviour change was on something undocumented, so I wouldn't consider it too annoying a problem - if you're using undocumented features, you have no guarantees for stability.

That being said, if presentation MathML + a TeX annotation is a useful output for math for you, we ought to support it (and it ought to be easy).

There actually used to be an option called ```--keepTeX``` which was specifically triggering adding the TeX annotation. And given that we already have 4 math output options, adding a fifth is probably fine. Not sure myself, but I don't feel strongly opposed, given we've caused a user some pain.

**Comment by fred-wang** [comment] 2015-05-15 13:27
> The regression + behaviour change was on something undocumented, so I wouldn't consider it too annoying a problem - if you're using undocumented features, you have no guarantees for stability.

Well sure, but I was not "using" a feature explicitly but "relying" on the default behavior. AFAIK, the LaTeX documentation does not mention the presence of the altext attribute and, still if LaTeXML suddendly stops generating the altext, you would probably consider this a serious issue to fix... (and if not, then all of this should probably be documented!)

The previous behavior was to always have a LaTeX annotation so I know what to expect. The current situation is not good: by default I don't have LaTeX (which is fine, I didn't ask it), if I specify -pmml I still don't have LaTeX (which is still ok, I didn't ask it and -pmml is the default), if I specify -pmm -cmml I now get a LaTeX annotation  (wait, I never asked it? And it's not mentioned on http://dlmf.nist.gov/LaTeXML/manual/usage/usage.post.html#SS0.SSS0.Px5. But actually can I generate only the LaTeX annotation? mmh, apparently no...). A --keepTeX option would make the behavior more predictable, in my opinion.

**Comment by dginev** [comment] 2015-05-15 13:33
```
all of this should probably be documented!)
```

I share this particular sentiment. 

```
The previous behavior was to always have a LaTeX annotation 
```

Sorry, but that's not factually correct. I think you used to have a default LaTeX annotation for some part of 2014 and 2015, but definitely not *always*. On the other hand, the ```alttext``` attribute has been there since at least 2007. But this isn't a constructive discussion to be having, let's figure out how to provide you with the behaviour you need, instead of pointing fingers.

Personally, I hadn't even realized Bruce changed the default behaviour, since I always use a specific set of math options for my applications, so he would have to explain that in more detail, if needed.

Your last comment of the predictability of the TeX annotation element is a good one. Reintroducing ```--keeptex``` is definitely a simple short-term solution. But I'd like to hear Bruce's thoughts on the matter.

**Comment by fred-wang** [comment] 2015-05-15 13:41
note: by "always", I meant "whatever the option you specify" not "LaTeXML has always generated it"

**Comment by brucemiller** [comment] 2015-05-15 13:46
I'm not even sure myself that I was aware I'd changed a default behaviour! And in fact, I'd kinda forgotten about the keepTeX option, as well! Things change, hopefully for the better usually, and some bugs are features!

At any rate, I think Fred's point on consistency makes good sense: Reintroduce a keepTeX option, and *only* add an annotation when that option is true (whether or not you are also asking for parallel markup). And, I'm glad Deyan agrees...

**Comment by dginev** [comment] 2015-05-15 13:47
Sounds great, let's execute that.

**Comment by brucemiller** [comment] 2015-05-24 15:12
I've just checked in a set of changes that adds a trivial math postprocessor, and only adds the TeX annotation when it's explicitly asked for.  The new option is called ```--mathtex``` which seems slightly more sensible than the old ```--keeptex``` (and I guess I'm stuck with ```--keepXMath``` for historical reasons).

Thanks for raising this issue.

**Closed by brucemiller** 2015-05-24 15:12 UTC
Labels: postprocessing, regression

**Comment by dginev** [comment] 2015-05-24 15:51
All the more reason for a minor CPAN release, I am also requesting one in #615 . And by that I mean v0.8.1.1
