### ISSUE TITLE
latexmlc does not open the documentation

### ISSUE THREAD

**Issue by matteosecli** [brucemiller/LaTeXML#792] opened 2016-07-25 13:40 UTC
Up to a few weeks ago, the commands `latexml* --help` used to print the help directly in the terminal.

Then, the behavior changed into printing just the version information and opening the man page (which is fine for me). On the latest git version & Ubuntu 14.04, the commands `latexml --help` and `latexmlpost --help` are equivalent to `man latexml` and `man latexmlpost` (at least, on my system).

However, `latexmlc` does not follow this behavior. The command `latexmlc --help` just prints the version number on the terminal and nothing else. If I try to access the man page via `man latexmlc`, I get a quite scant manpage with the following synopsis:
```
SYNOPSYS
       See the OPTIONS section in LaTeXML::Common::Config for usage
       information.
         Also consult latexmlc --help
```
To get a clue of what the options for `latexmlc` are, I have to type `man LaTeXML::Common::Config` and go through a couple of screens before getting into the section "OPTION SYNOPSIS" that indeed describes the options for `latexmls/latexmlc`.

I think this is not really "user friendly", since it makes quite hard for a user to find the information he is looking for. It would be nice, imho, to

- at least redirect `latexmlc --help` to `man latexmlc`, as it already happens with `latexml` and `latexmlpost`;
- create a separate manpage for `latexmlc`, as it used to be a few weeks ago (afair).

I hope this is not just a problem with my configuration, so let me kindly know if you can reproduce the bug.

**Comment by dginev** [comment] 2016-07-25 14:29
I think latexmlc never printed the full help on screen. It's a bit of a tricky thing there, since I've been meaning to reuse the POD in Common::Config, but I never found out how without copying it verbatim.

So this is not a regression, latexmlc has always been a little different is all. It's a good request to make this better.

**Comment by dginev** [comment] 2016-07-29 00:52
In the end you were right - I actually had some smart code in place that was displaying the synopsis from Common::Config on ```latexmlc --help```. But as I rearranged the docs, the selector failed. Pull request is now in - should be fixed soon.

Thanks for the report, very helpful!

**Closed** 2016-07-29 19:30 UTC
Labels: bug, documentation

**Comment by matteosecli** [comment] 2016-07-31 10:11
Glad it's been helpful! :smiley: 
I've just tested the latest revision and indeed now `latexmlc --help` displays the options as expected.
