### ISSUE TITLE
Add support/a binding for pgfplotstable.sty

### ISSUE THREAD

**Issue by 0jg** [brucemiller/LaTeXML#1304] opened 2020-07-03 15:51 UTC
cc @bfirsh 

Unsure if this is a general issue, or if it is specific to `pgfplotstable`. I have two LaTeX packages imported in the same line in the preamble:

```
\usepackage{pgfplots,pgfplotstable}
```

which returns the error for a tikz figure in the main body of the LaTeX when using arxivvanity/engrafo 

```
Error:latex:\GenericError Package pgfplotstable Error: Please load \usepackage{pgfplotstable} before using \pgfplotstablecreatecol
	at main.tex; line 759 col 0 - line 759 col 64
	See the pgfplotstable package documentation for explanation.
	In Core::Definition::Primitive[\GenericE... /usr/local/share/perl/5.30.0/LaTeXML/Package/LaTeX.pool.ltxml; line 5070
	 <= Core::Stomach[@0x55635732e570] <= Core::Definition::Primitive[Begin] <= Core::Stomach[@0x55635732e570] <= ...
```

Can you confirm if multiple packages can be listed in the same command? If not, could this be implemented?

JG

**Comment by dginev** [comment] 2020-07-03 15:57
This is certainly specific to `pgfplotstable`, in combination with the texlive used. I am also assuming you're using the `--includestyles` switch to load it raw?

Here's the loading log I see on texlive 2019 with the latest latexml:
<details>

```
$ latexmlc --includestyles test.tex --dest=test.html

(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/TeX.pool.ltxml...
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/eTeX.pool.ltxml... 0.00 sec)
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/pdfTeX.pool.ltxml... 0.00 sec) 0.08 sec)

latexmlc (LaTeXML version 0.8.4; revision c3853236)
processing started Fri Jul  3 11:54:49 2020

(Digesting TeX test...
(Processing content /tmp/test.tex...
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/LaTeX.pool.ltxml... 0.11 sec)
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/article.cls.ltxml... 0.01 sec)
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/pgfplots.sty.ltxml...
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/pgfplots/pgfplots.sty...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.revision.tex... 0.00 sec)
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/graphicx.sty.ltxml...
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/graphics.sty.ltxml... 0.00 sec) 0.01 sec)
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/tikz.sty.ltxml...
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty...
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/pgf.sty.ltxml...
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty...
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty...
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/pgfutil-common.tex.ltxml...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common-lists.tex... 0.02 sec) 0.10 sec) 0.10 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def...
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/ms/everyshi.sty... 0.01 sec) 0.04 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/pgf.revision.tex... 0.00 sec) 0.02 sec) 0.24 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty...
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex...
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/pgfkeys.code.tex.ltxml...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.tex... 0.13 sec) 0.32 sec) 0.32 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg... 0.00 sec)Driver file for pgf: pgfsys-latexml.def

(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/pgfsys-latexml.def.ltxml... 0.01 sec) 0.72 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.tex... 0.02 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.tex... 0.01 sec) 0.75 sec)
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/keyval.sty.ltxml...
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex-dev/graphics/keyval.sty... 0.01 sec) 0.01 sec)
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/xcolor.sty.ltxml...
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/color.sty.ltxml... 0.01 sec) 0.04 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex...
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/pgfmath.code.tex.ltxml...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex...
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/pgfmathcalc.code.tex.ltxml...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex... 0.06 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex... 0.22 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code.tex... 0.22 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonometric.code.tex... 0.98 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.code.tex... 0.03 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison.code.tex... 0.16 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.tex... 0.08 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code.tex... 0.04 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.tex... 0.10 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerarithmetics.code.tex... 0.04 sec) 1.69 sec) 2.00 sec) 2.00 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex... 0.47 sec) 2.48 sec) 2.49 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfint.code.tex... 0.01 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.tex... 0.12 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.code.tex... 0.11 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code.tex... 0.08 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.tex... 0.08 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.code.tex... 0.02 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformations.code.tex... 0.06 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex... 0.01 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.tex... 0.01 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing.code.tex... 0.04 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.tex... 0.47 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex... 0.09 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.tex... 0.06 sec) 0.10 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.tex... 0.02 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.code.tex... 0.03 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.tex... 0.03 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex... 0.01 sec) 3.80 sec) 4.61 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex... 0.18 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex... 0.09 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65.sty... 0.23 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18.sty... 0.01 sec) 5.39 sec) 5.39 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgffor.sty...
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty... 0.00 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/pgf/math/pgfmath.sty... 0.01 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex... 0.09 sec) 0.11 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers.code.tex... 0.10 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex... 0.05 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarytopaths.code.tex... 0.08 sec) 1.47 sec) 6.98 sec) 6.98 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotscore.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/sys/pgfplotssysgeneric.code.tex... 0.01 sec) 0.24 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/pgfplotslibrary.code.tex... 0.01 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/oldpgfcompatib/pgfplotsoldpgfsupp_loader.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryfpu.code.tex... 0.26 sec) 0.31 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsliststructure.code.tex... 0.03 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsliststructureext.code.tex... 0.06 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsarray.code.tex... 0.06 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsmatrix.code.tex... 0.05 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/numtable/pgfplotstableshared.code.tex... 0.39 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/liststructure/pgfplotsdeque.code.tex... 0.01 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsbinary.data.code.tex... 0.16 sec) 0.23 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotsutil.verb.code.tex... 0.02 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/pgflibrarypgfplots.surfshading.code.tex... 0.28 sec) 1.44 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotscolormap.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/util/pgfplotscolor.code.tex... 0.09 sec) 1.22 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsstackedplots.code.tex... 0.05 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsplothandlers.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplothandler.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsmeshplotimage.code.tex... 0.04 sec) 0.57 sec) 1.26 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.scaling.code.tex... 0.24 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotscoordprocessing.code.tex... 1.19 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.errorbars.code.tex... 0.05 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.markers.code.tex... 0.03 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplotsticks.code.tex... 0.19 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/pgfplots.paths.code.tex... 0.01 sec)
TIKZ LIBRARY decorations

(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarydecorations.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduledecorations.code.tex... 0.24 sec) 0.29 sec)
TIKZ LIBRARY decorations.pathmorphing

(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarydecorations.pathmorphing.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.pathmorphing.code.tex... 0.09 sec) 0.10 sec)
TIKZ LIBRARY decorations.pathreplacing

(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarydecorations.pathreplacing.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.pathreplacing.code.tex... 0.07 sec) 0.09 sec) 38.46 sec)
TIKZ LIBRARY plotmarks

(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibraryplotmarks.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplotmarks.code.tex... 0.07 sec) 0.08 sec) 45.64 sec) 46.35 sec)
(Processing definitions /usr/share/texlive/texmf-dist/tex/latex/pgfplots/pgfplotstable.sty...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/numtable/pgfplotstable.code.tex...
(Processing definitions /usr/share/texlive/texmf-dist/tex/generic/pgfplots/numtable/pgfplotstable.coltype.code.tex... 0.01 sec) 0.86 sec)
(Loading /home/deyan/perl5/lib/perl5/LaTeXML/Package/array.sty.ltxml... 0.00 sec) 0.87 sec)ABD: EveryShipout initializing macros
Warning:latex:\GenericWarning (pgfplots)                
	at test.tex; line 3 col 0 - line 3 col 16
	Package pgfplots Warning: running in backwards compatibility mode (unsuitable tick labels; missing features). Consider writing \pgfplotsset{compat=1.16} into your preamble.
	In Core::Definition::Primitive[\GenericW... /home/deyan/perl5/lib/perl5/LaTeXML/Package/LaTeX.pool.ltxml; line 5073
 47.35 sec) 47.35 sec)
(Building...
(Loading compiled schema /home/deyan/perl5/lib/perl5/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.01 sec). 0.03 sec)
(Rewriting... 0.00 sec)
(Finalizing... 0.00 sec)
Conversion complete: 1 warning.

(post-processing...
(Scan test.html processing... 0.00 sec)
(CrossRef test.html processing... 0.00 sec)
(XSLT[using LaTeXML-html5.xsl] test.html processing... 0.00 sec)
(Writer test.html processing... 0.00 sec) 0.00 sec)
Post-processing complete: No obvious problems
processing finished Fri Jul  3 11:55:37 2020
Status:conversion:1 
1 warning
No obvious problems
Wrote test.html

```

</details>

for 
```tex
\documentclass{article}
\usepackage{pgfplots,pgfplotstable}
\begin{document}
a
\end{document}
```

So the package does load, but it looks like the raw interpretation has triggered its TeX error-handling checks, so we may need to add a dedicated binding to proceed error-free.

**Comment by dginev** [comment] 2020-07-03 15:59
Feel free to send us a link to the original paper, may be able to find a quick fix.

**Comment by j-griffiths** [comment] 2020-07-03 16:46
> Feel free to send us a link to the original paper, may be able to find a quick fix.

Cheers for the additional info. The paper repo available here: [https://github.com/j-griffiths/diss](url). All the LaTeX is in diss.tex.

**Comment by dginev** [comment] 2020-07-03 23:02
Is this supposed to build with `xelatex diss.tex`? I am failing to do so locally, getting a wide range of errors.

Indeed the error you are seeing with latexml happens due to `pgfplotstable` not having an official latexml binding, so you are getting a generic error telling you it wasn't loaded. The correct path forward would be to create (or request) an official binding for `pgfplotstable.sty.ltxml`. The brave approach is to simply add `--includestyles` to your latexml call and have it load the raw style directly.

I tried that, but sadly there are a range of related errors, that would require properly focusing on the package support.

The additional bad news is that since your thesis document has a LaTeX 3 dependencies (via another unsupported package - mathspec.sty), which we're currently working on recovering (regression issue at #1278 ).

I can't offer a quick resolution here after all, and can suggest one of the following:
 * giving up for now and closing the issue,
 * leaving the issue open an renaming it as `add support for pgfplotstable.sty`

The positive news, as scarce as that seems, is that `\usepackage` works correctly, that was only the first symptom hinting of the issue.

**Comment by dginev** [comment] 2020-07-03 23:07
A meta comment: currently succeeding to convert a book-sized document with latexml is considered a notable success. It is usual in documents of this size to reach for some of the rarer pieces of the LaTeX ecosystem, and latexml's coverage is still some distance from "full LaTeX". It is a rare occasion to have an entire thesis succeed building on the first try for example. Our main development target is one very specific book-sized project [NIST's DLMF](https://dlmf.nist.gov/), and the main extended stress test is the average document on arXiv.org, which is usually a short-form paper, simpler in typesetting complexity compared to a book or thesis.

**Comment by j-griffiths** [comment] 2020-07-04 10:52
Thanks for the additional testing and information—indeed the length of the thesis is more of an edge-case. The aforementioned plotting package is used by other researchers—and their papers which are on the arXiv—so I will re-name this issue and leave it open so an official binding can be created. Cheers! :)

**Comment by j-griffiths** [comment] 2020-07-04 10:55
Aside: this is indeed compiled by xetex—I understand that this is not yet supported (correct me if I am wrong!). Thanks for verifying that the issue still exists in LaTeXML.

**Comment by dginev** [comment] 2020-07-04 15:28
In general latexml can emulate all of the various toolchains, as long as you don't need some of their special customization as a must-have. E.g. we can't run a lua interpreter for special `lualatex` runs. But as far as unicode support is considered, which is the major win of xetex/xelatex, latexml is already quite capable with working with unicode documents, so it should have a successful conversion without any issues.

The root cause is the pgplotstable package for your report here, thanks for renaming the issue, and for reporting it in!

**Comment by brucemiller** [comment] 2020-12-28 13:09
I've recently been working in pgf/tikz regressions, but I suspect that this package is not yet going to yield. Although it  does load (with `--includestyles`), since it involves tables, I expect it won't work until we have better support for TeX-level alignments (`\halign`).  But, being late to the game, I can no longer access your sample to be sure.

**Comment by j-griffiths** [comment] 2020-12-28 13:15
> I've recently been working in pgf/tikz regressions, but I suspect that this package is not yet going to yield. Although it does load (with `--includestyles`), since it involves tables, I expect it won't work until we have better support for TeX-level alignments (`\halign`). But, being late to the game, I can no longer access your sample to be sure.

Thanks for the update. I've temporarily made the sample repo private, but I have added you as a collaborator until I make it public again. Maybe this will be of use!

**Comment by brucemiller** [comment] 2021-08-07 20:58
@0jg: I was just taking a peek to see if any of this would work, but hit a stumbling block in that there seem to be missing data files (`data/zt_jj.csv` and `data/ft_jj.csv`), but maybe I've misunderstood.

**Comment by dginev** [comment] 2021-08-09 21:38
The latest latexml has (unintentionally really) made progress on basic support for `pgfplotstable.sty`, via raw interpretation. A minimal example that worked great:

```tex
% Example taken from https://reijz.github.io/2016/01/25/pgfplotstable.html
\documentclass{article}
\usepackage{pgfplots,pgfplotstable}
\usepackage{colortbl}
\begin{document}
\pgfplotstabletypeset[
	col sep=comma,
	columns/E/.style={string type},
	every even column/.style={column type/.add={>{\columncolor[gray]{.8}}}{}}
]{example.csv}

\vspace{2em}

\pgfplotstabletypeset[
	col sep=comma,
	columns/E/.style={string type},
	every even row/.style={before row={\rowcolor[gray]{.8}}}
]{example.csv}
\end{document}
```

example.csv contains:
```csv
1, 10, 0.1, 1000
2, 20, 0.2, 2000
3, 30, 0.3, 3000
4, 40, 0.4, 4000
5, 50, 0.5, 5000
```

Then, saving that in test.tex and running:
```
latexmlc test.tex --dest=test.html --includestyles
```

yields the decent-looking HTML:
<img width=600 src="https://user-images.githubusercontent.com/348975/128777602-63543892-b2b2-4f60-8d4f-3aae912ea6cc.png">

Maybe I should consider adding a binding file that allows interpreting `pgfplotstable.sty` raw at this point, @brucemiller ?

**Comment by 0jg** [comment] 2021-08-10 12:10
> @0jg: I was just taking a peek to see if any of this would work, but hit a stumbling block in that there seem to be missing data files (`data/zt_jj.csv` and `data/ft_jj.csv`), but maybe I've misunderstood.

Apologies—I think this folder was omitted from that repo. Here are the two data files.

[data.zip](https://github.com/brucemiller/LaTeXML/files/6961535/data.zip)

**Comment by 0jg** [comment] 2021-08-10 12:12
> The latest latexml has (unintentionally really) made progress on basic support for `pgfplotstable.sty`, via raw interpretation. A minimal example that worked great:
> 
> ```
> % Example taken from https://reijz.github.io/2016/01/25/pgfplotstable.html
> \documentclass{article}
> \usepackage{pgfplots,pgfplotstable}
> \usepackage{colortbl}
> \begin{document}
> \pgfplotstabletypeset[
> 	col sep=comma,
> 	columns/E/.style={string type},
> 	every even column/.style={column type/.add={>{\columncolor[gray]{.8}}}{}}
> ]{example.csv}
> 
> \vspace{2em}
> 
> \pgfplotstabletypeset[
> 	col sep=comma,
> 	columns/E/.style={string type},
> 	every even row/.style={before row={\rowcolor[gray]{.8}}}
> ]{example.csv}
> \end{document}
> ```
> 
> example.csv contains:
> 
> ```
> 1, 10, 0.1, 1000
> 2, 20, 0.2, 2000
> 3, 30, 0.3, 3000
> 4, 40, 0.4, 4000
> 5, 50, 0.5, 5000
> ```
> 
> Then, saving that in test.tex and running:
> 
> ```
> latexmlc test.tex --dest=test.html --includestyles
> ```
> 
> yields the decent-looking HTML:
> <img alt="" width="600" src="https://user-images.githubusercontent.com/348975/128777602-63543892-b2b2-4f60-8d4f-3aae912ea6cc.png">
> 
> Maybe I should consider adding a binding file that allows interpreting `pgfplotstable.sty` raw at this point, @brucemiller ?

This does look good! Is the HTML semantic?

**Comment by dginev** [comment] 2021-08-10 12:48
> Is the HTML semantic?

That depends on what your question expects that word to mean for HTML. But by default, raw interpretation doesn't capture any high-level structure, and stays low-level + presentation (i.e. *not* semantic). There needs to be a latexml binding intervention whenever one wants better markup.

The examples above are two tables with `th` elements for the headers, as expected body, rows and columns, and `style` attributes for the background color. A binding could instead add class annotations. The data is in `<math>` elements, and `<mn>` elements for the numbers, respectively. That said `1,000` is not tokenized to a single `mn` element as the coma is deposited as an operator.

So it could be improved. But again - curious what you expect the best "semantic" markup to be for a numeric table in HTML.

**Closed** 2021-08-24 16:06 UTC
Labels: bug, packages
