### ISSUE TITLE
Incorrect DOCTYPE declaration

### ISSUE THREAD

**Issue by delta-river** [brucemiller/LaTeXML#1702] opened 2021-10-27 08:37 UTC
## Problem

When executing the following command:

```
latexmlc --format=html5 --inputencoding=utf8 --dest=$OUTPUT $INPUT
```

the DOCTYPE declaration in the output html is escaped by HTML character references as the following:

```
&lt;!DOCTYPE html&gt;<html>
```

where it should be as the following:

```
<!DOCTYPE html>
```

## Environment

I'm running the command on Ubuntu 20 on WSL2 with LaTeXML v0.8.5 (though the same problem also occurs with v0.8.6).

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
$ latexmlc --VERSION
latexmlc (LaTeXML version 0.8.5; revision 13f394ec)
```

```
$ xslt-config --version
1.1.34
```

## Example Run

```
$ latexmlc --format=html5 --inputencoding=utf8 --dest=./output.html ./LaTeXML/t/theorem/theorem.tex
latexmlc (LaTeXML version 0.8.5; revision 13f394ec)
processing started Wed Oct 27 17:32:04 2021
Conversion complete: No obvious problems
Post-processing complete: No obvious problems
Status:conversion:0
```

Then, the `output.html` starts with

```
&lt;!DOCTYPE html&gt;<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Corollary 1</title>
<!--Generated on Wed Oct 27 17:32:05 2021 by LaTeXML (version 0.8.5) http://dlmf.nist.gov/LaTeXML/.-->
```

**Comment by delta-river** [comment] 2021-11-02 08:25
Thank you for the reply!!

I checked out `v0.8.6` and executed  `cpanm .` in the LaTeXML repository. However, it didn't fix the problem...
The version of latexmlc after checking out is as follows:

```
$ latexmlc --VERSION
latexmlc (LaTeXML version 0.8.6; revision be6bbab5)
```

By the way, I installed libxml and libxslt by the following command:

```
sudo apt-get install libxml-libxslt-perl
```
( though, I'm not sure if this is related or not...)

**Comment by dginev** [comment] 2021-11-03 13:20
@delta-river just to confirm, when you run `cpanm .`  does latexml install with all tests passing?

If so, this is extra strange, as `latexmlc` has a suite of tests which will be writing in this doctype declaration as part of the installation, and you should see things fail.

**Comment by delta-river** [comment] 2021-11-09 05:26
I executed `cpanm . --verbose >& ../opanm_results.txt` .

The output says "All tests successful.", though some tests were skipped due to "Missing requirement". 

Followings are some examples of "Missing requirement":

```
# Skip: Missing requirement latin3.def for t/encoding/latin3
# Skip: Missing requirement latin4.def for t/encoding/latin4
# Skip: Missing requirement latin5.def for t/encoding/latin5
# Skip: Missing requirement latin9.def for t/encoding/latin9
# Skip: Missing requirement ly1enc.def for t/encoding/ly1
# Skip: Missing requirement ot1enc.def for t/encoding/ot1
# Skip: Missing requirement t1enc.def for t/encoding/t1
```

But, I am not sure if the skipped cases are critical here.

This ↓ is the full output (about 800 lines).
[opanm_results.txt](https://github.com/brucemiller/LaTeXML/files/7502030/opanm_results.txt) (I modified the username and the path to LaTeXML to "USERNAME" and "PATHTO" respectively.)

**Comment by delta-river** [comment] 2021-11-09 07:28
I prepared a clean Ubuntu 20.04.3 (which is a little bit different from the above environment (Ubuntu 20.04.2) though) and rebuild LaTeXML. But, I couldn't reproduce the DOCTYPE declaration problem...

I suppose there is something wrong in my environment and the current LaTeXML tests cannot detect it.

## Environment

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
$ latexmlc --VERSION
latexmlc (LaTeXML version 0.8.6; revision be6bbab5)
```

```
$ xslt-config --version
1.1.34
```

## Environment Preparation

```
sudo apt update
sudo apt install make
sudo apt-get install libxml-libxslt-perl
sudo apt install libxslt1-dev
sudo apt install gcc

curl -L https://cpanmin.us | perl - App::cpanminus
```

```
git clone https://github.com/brucemiller/LaTeXML.git
cd LaTeXML
git checkout v0.8.6
cpanm .
```
and adding the followings to `.bashrc`:

```
export PATH=$HOME/perl5/bin:$PATH
export PERL5LIB=$HOME/perl5/lib/perl5:$PERL5LIB
export PATH=$HOME/LaTeXML/bin:$PATH
```

## Example Run

```
$ latexmlc --format=html5 --inputencoding=utf8 --dest=./output.html ./LaTeXML/t/theorem/theorem.tex
latexmlc (LaTeXML version 0.8.6; revision be6bbab5)
processing started Tue Nov  9 16:08:45 2021
Conversion complete: No obvious problems
Post-processing complete: No obvious problems
Status:conversion:0
```

```
$ cat output.html | head
<!DOCTYPE html><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Corollary 1</title>
<!--Generated on Tue Nov  9 16:08:45 2021 by LaTeXML (version 0.8.6) http://dlmf.nist.gov/LaTeXML/.-->

<link rel="stylesheet" href="LaTeXML.css" type="text/css">
<link rel="stylesheet" href="ltx-article.css" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
```

**Comment by delta-river** [comment] 2021-11-09 07:55
Besides, I tried installing latexml by `sudo apt-get install latexml` on my original buggy environment (Ubuntu 20.04.2). However, it did not fix the incorrect DOCTYPE declaration problem.

**Comment by dginev** [comment] 2021-12-15 01:31
Since I have no way to reproduce the doctype issue, I'll close here for now as "wontfix" - sorry about which. If we find a stable way to produce the broken behavior, feel free to reopen.

**Closed by dginev** 2021-12-15 01:31 UTC
Labels: bug, latexml
