### ISSUE TITLE
Problem with cmap.sty

### ISSUE THREAD

**Issue by henrikt-ma** [brucemiller/LaTeXML#2035] opened 2022-12-18 20:35 UTC
This doesn't work unless the use of _cmap.sty_ is removed:
```
\documentclass{article}
\usepackage{cmap}
\usepackage[utf8]{inputenc}
\usepackage{natbib}
\begin{document}
Broken citation: \cite{Hello}
\bibliography{minimal}
\end{document}
```

Symptom: Citation just shows bibliography key, like this:
> Broken citation: Hello

and the bibliography is empty.

This is the corresponding _minimal.bib_:
```
@InProceedings{Hello,
  author = {Lastname, Firstname},
  title = {Hello},
}
```

Build rule:
```
minimal.html: minimal.tex
	$(LATEXMLPREFIX)latexml minimal.tex --includestyles --dest minimal.xml
	$(LATEXMLPREFIX)latexmlpost minimal.xml -format html -pmml --navigationtoc=context --dest $@
```

Build log:
```
➜  minimal-LaTeXML touch minimal.tex;make minimal.html
latexml minimal.tex --includestyles --dest minimal.xml
latexml (LaTeXML version 0.8.6) processing minimal.tex
Error:expected:{} Missing argument {} for Core::Definition::Expandable[\@gobble {}] at cmap.sty; line 43 col 0
Warning:latex:(cmap) Package cmap Warning: pdftex not detected - exiting at cmap.sty; line 43 col 0
Conversion complete 1 warning; 1 error (See /Users/henrikt/Documents/minimal-LaTeXML/minimal.latexml.log) (reqd. 0.53s)
latexmlpost minimal.xml -format html -pmml --navigationtoc=context --dest minimal.html
latexmlpost (LaTeXML version 0.8.6) paginating /Users/henrikt/Documents/minimal-LaTeXML/minimal.xml
Error:expected:{} Missing argument {} for Core::Definition::Expandable[\@gobble {}] at cmap.sty; line 43 col 0
Warning:latex:(cmap) Package cmap Warning: pdftex not detected - exiting at cmap.sty; line 43 col 0
Initialization complete: 1 warning; 1 error (See /Users/henrikt/Documents/minimal-LaTeXML/minimal.latexmlpost.log). Aborting.
Error:expected:{} Missing argument {} for Core::Definition::Expandable[\@gobble {}] at cmap.sty; line 43 col 0
Warning:latex:(cmap) Package cmap Warning: pdftex not detected - exiting at cmap.sty; line 43 col 0
Initialization complete: 1 warning; 1 error (See /Users/henrikt/Documents/minimal-LaTeXML/minimal.latexmlpost.log). Aborting.
Warning:expected:bibkeys Missing bibkeys hello
Warning:expected:ids Missing Entry for citation: Hello
Postprocessing complete 2 warnings (reqd. 0.62s)
```

As mentioned in https://github.com/brucemiller/LaTeXML/issues/2033#issuecomment-1353165816 I have a suspicion that this could have worked with LaTeXML 0.8.5, but after having narrowed it down to _cmap.sty_ I would like to check this once more.  Unfortunately, I don't have access to my computer where 0.8.5 is still installed right now, but I might get a chance to check later this week…

**Comment by teepeemm** [comment] 2022-12-19 22:40
I think the problem is `\PackageWarningNoLine`:
```tex
\documentclass{article}
\PackageWarning{mypackage}{this is ok}
\PackageWarningNoLine{mypackage}{this is not}
\begin{document}
hi
\end{document}
```
gives the same error.  It looks like LaTeX(ML) defines `\PackageWarningNoLine{}{}` to become `\PackageWarning{#1}{#2\@gobble}`.  I'm not sure what happens after that in either engine, but `latexml` complaining about `\@gobble` missing an argument `{}` seems plausable.

A different approach to fixing cmap (but not `\PackageWarningNoLine`) would be to define `cmap.sty.ltxml`.  Since the point of `cmap.sty` is to enable searching and copy/paste in a pdf, I don't think we actually need to do anything, and could just make the contents of the binding: `1;`.

**Comment by teepeemm** [comment] 2023-07-21 18:52
@dginev Since we've implemented cmap and fixed `\PackageWarningNoLine`, I believe this issue can be resolved.

**Comment by dginev** [comment] 2023-07-21 20:04
Indeed, a quick conversion check with the reported example and the latest latexml master seems to work out correctly.

Closing here, thanks for monitoring @teepeemm

**Closed by dginev** 2023-07-21 20:04 UTC
Labels: bug, packages
