### ISSUE TITLE
expl3 again

### ISSUE THREAD

**Issue by Jazzpirate** [brucemiller/LaTeXML#2124] opened 2023-06-15 06:54 UTC
latexml dies with `Fatal:timeout:timedout Conversion timed out at expl3-code.tex; line 31907 col 7 - line 31907 col 7`
Current version/revision (0.8.7; eb778a28)
TeXLive 2023 - I got the error with a version from two months ago; just updated all packages (including expl) and the problem persists; the above line/col info is from the *current* version of expl3 (from 5th of June, apparently)

**Comment by dginev** [comment] 2023-06-15 10:37
Thanks for the report Dennis!

I believe this is a duplicate of #2064 so I will close this issue to keep the reports focused. Bruce is actively working on improving the expl3 support with the latest texlives.

The usual short-term resolution I can advise is to downgrade to a texlive from a year or two ago, where we expect better latexml support for expl3.

**Closed by dginev** 2023-06-15 10:37 UTC
Labels: regression, duplicate

**Comment by Jazzpirate** [comment] 2023-06-15 10:40
I found that one as well, but wasn't sure if it's actually the same issue - in my case, I actually get a timedout error (after something like 10min of expl processing), whereas Bruce's comment over there seems to indicate that the issue is somewhere else... either way, you're informed now :)
