### ISSUE TITLE
Defend against unrecoverable ghostscript error

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#673] opened 2015-10-18 21:37 UTC
This error, caught from the arXiv conversion harness, seems to terminate processes in a "dirty" manner, as I have seen my latexml workers quietly die with this being the last caught trace in STDERR. Sadly I don't have an example that can reproduce this problem (yet), but there are good hints as to how to reproduce it.

I wonder if the "fork on image convert" approach described in #663 would also help us protect against these issues. 

>Can't find the font file /usr/share/fonts/truetype/fonts-japanese-mincho.ttf
Error: /undefinedfilename in /findfont
Operand stack:
   --nostringval--   18.0   Ryumin-Light-83pv-RKSJ-H
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1910   1   3   %oparray_pop   1909   1   3   %oparray_pop   --nostringval--   1893   1   3   %oparray_pop   1787   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   1868   3   4   %oparray_pop
Dictionary stack:
   --dict:1166/1684(ro)(G)--   --dict:0/20(G)--   --dict:84/200(L)--   --dict:144/300(L)--
Current allocation mode is local
Last OS error: No such file or directory
Current file position is 46995
GPL Ghostscript 9.05: Unrecoverable error, exit code 1
Can't find the font file /usr/share/fonts/truetype/fonts-japanese-mincho.ttf
Error: /undefinedfilename in /findfont
Operand stack:
   --nostringval--   18.0   Ryumin-Light-83pv-RKSJ-H
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1910   1   3   %oparray_pop   1909   1   3   %oparray_pop   --nostringval--   1893   1   3   %oparray_pop   1787   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   1868   3   4   %oparray_pop
Dictionary stack:
   --dict:1166/1684(ro)(G)--   --dict:0/20(G)--   --dict:84/200(L)--   --dict:144/300(L)--
Current allocation mode is local
Last OS error: No such file or directory
Current file position is 46995
GPL Ghostscript 9.05: Unrecoverable error, exit code 1
Can't find the font file /usr/share/fonts/truetype/fonts-japanese-mincho.ttf
Error: /undefinedfilename in /findfont
Operand stack:
   --nostringval--   18.0   Ryumin-Light-83pv-RKSJ-H
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1910   1   3   %oparray_pop   1909   1   3   %oparray_pop   --nostringval--   1893   1   3   %oparray_pop   1787   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   1868   3   4   %oparray_pop
Dictionary stack:
   --dict:1166/1684(ro)(G)--   --dict:0/20(G)--   --dict:84/200(L)--   --dict:143/300(L)--
Current allocation mode is local
Last OS error: No such file or directory
Current file position is 24336
GPL Ghostscript 9.05: Unrecoverable error, exit code 1
Can't find the font file /usr/share/fonts/truetype/fonts-japanese-mincho.ttf
Error: /undefinedfilename in /findfont
Operand stack:
   --nostringval--   18.0   Ryumin-Light-83pv-RKSJ-H
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1910   1   3   %oparray_pop   1909   1   3   %oparray_pop   --nostringval--   1893   1   3   %oparray_pop   1787   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   1868   3   4   %oparray_pop
Dictionary stack:
   --dict:1166/1684(ro)(G)--   --dict:0/20(G)--   --dict:84/200(L)--   --dict:143/300(L)--
Current allocation mode is local
Last OS error: No such file or directory
Current file position is 24336
GPL Ghostscript 9.05: Unrecoverable error, exit code 1

**Comment by brucemiller** [comment] 2015-10-18 23:50
On 10/18/2015 05:37 PM, Deyan Ginev wrote:
> This error, caught from the arXiv conversion harness, seems to terminate
> processes in a "dirty" manner, as I have seen my latexml workers quietly
> die with this being the last caught trace in STDERR. Sadly I don't have
> an example that can reproduce this problem (yet),

You mean the document that was being processed doesn't always
cause the error? That's pretty difficult to narrow down, then.

**Comment by dginev** [comment] 2015-10-19 00:36
No, it probably always does generate this error, I just don't know which paper it is yet.

This error got flushed to the actual STDERR and there are 15 parallel workers that could have been the source of the issue, I think it managed to kill all of them. Will get to it eventually.

**Comment by brucemiller** [comment] 2015-10-21 15:42
but isn't this just a duplicate of #663?

**Closed by brucemiller** 2015-10-21 15:42 UTC
Labels: duplicate, enhancement, question

**Comment by dginev** [comment] 2015-10-21 15:45
Ok, I can live with having a single issue for all of the ImageMagick deaths :+1:
