### ISSUE TITLE
Cannot use non-html5 equations

### ISSUE THREAD

**Issue by ianhbell** [brucemiller/LaTeXML#809] opened 2016-11-02 16:49 UTC
First off, excellent work with this package.  I am able to convert a rather complex document to html5 with lots of equations and images.  Ultimately my target is to get back to a Word document from a latex document.  I think I am not far off.

That said, latexml always borks when I try to tell it to use svg or png equations (with ``--mathsvg`` or ``--mathimages`` respectively). The HTML5 equations will obviously be no good in Word.

I always get this error: 
```
Fatal:perl:die Perl died
	Postprocessing LaTeXML::Post::MathML::Presentation Paper.html
	Wide character in subroutine entry at /usr/share/perl5/LaTeXML/Post.pm line 1188.
```
It would be nicer if the error would not kill LateXML, rather it would just skip that equation.

**Comment by ianhbell** [comment] 2016-11-02 22:43
It turns out the offending character was a en-dash from the cp1252 character set (as in not the ASCII dash). This bad guy: http://unicode-table.com/en/2013/

**Comment by dginev** [comment] 2016-11-03 07:01
Was that character in the original input document, or it was created internally during math parsing?

Very valid bug request here, will be fixed.

**Comment by ianhbell** [comment] 2016-11-03 15:54
It was in the original LaTeX document.  Actually, I had converted a Word document to LaTeX by copy-paste (not the most elegant solution, but the fine-tuning was simple enough).  I think that's how the character ended up there.  The en-dash are a real pain from the copy-paste standpoint.

**Comment by dginev** [comment] 2016-11-03 15:55
That said, it shouldn't really break latexml, which is unicode-aware. Could you share the formula that had the unicode dash with us? Maybe we can use it to reproduce and find an elegant fix.

**Comment by ianhbell** [comment] 2016-11-03 16:00
Perhaps this would do it (it was actually an inline equation, but I think the problem is the same):

$s_{\rm res}(T,\rho) = s(T,\rho) – s^0(T,\rho)$

**Comment by brucemiller** [comment] 2016-11-27 15:13
hmm, it seems that tied hashes don't like to get utf passed to them? I've patched that up and it runs without error (or even warning).  However, I wonder that it gives what you want: LaTeX (even outside of LaTeXML) essentially ignores the en-dash; perhaps it was intended to be a minus?

**Closed by brucemiller** 2016-11-27 15:13 UTC
Labels: bug, postprocessing
