### ISSUE TITLE
latexmlpost randomly crashes on exit (alpine >= 3.13) 

### ISSUE THREAD

**Issue by stamer** [brucemiller/LaTeXML#1959] opened 2022-10-09 16:35 UTC
Current latexml master (LaTeXML version 0.8.6; revision 2f0c5a08) on alpine >=3.13 and alpine-edge.

(alpine 3.12 is ok, >=3.13 crashes)
When doing
wget https://raw.githubusercontent.com/stamer/texmlbus/master/volume/src/server/samples/samples/testmath-sample/testmath-sample.tex
latexml --destination testmath-sample.tex.xml testmath-sample.tex
latexmlpost --destination testmath-sample.xhtml testmath-sample.tex.xml
latexmlpost then crashes randomly on alpine >= 3.13. Sometimes the conversion is successfully completed.

In both cases the destination xhtml file is completely written, but 'Conversion complete' is never written to the log. (it crashes at
the end of eval()). It seems that latexmlpost crashes while freeing resources.  

This has been tested in virtual machines as well as in docker containers.
I have the impression that this seems to be an alpine/musl problem though, I have no problems with this file (and others) when
running  in current opensuse releases.

**Comment by dginev** [comment] 2022-10-09 16:52
@stamer do you know if alpine 3.12 has a different libxml2 installed than alpine 3.14 ? 

I think it would be helpful to know the version of that component as well.

**Comment by stamer** [comment] 2022-10-09 17:19
Sure, 
alpine 3.12 libxml2.2.9.14-r0
alpine 3.14 libxml2-2.9.14-r1
alpine 3.16 libxml2-2.9.14-r1
alpine edge libxml2-2.10.2-r1
opensuse tumbleweed libxml2-2.10.2-2.1
What puzzles me is that alpine edge also randomly crashes, while opensuse is fine.

**Comment by dginev** [comment] 2023-08-10 20:20
I know this is not the resolution you are hoping for @stamer, but since we can't reliably reproduce, I will go ahead and close with "wontfix" here.

It is likely a safe bet that we have some failure external to Perl, most likely when libxml frees its allocated memory at the end of processing.

If we had reliable steps to reproduce that we would certainly want to find a patch, but until then it may be worthwhile to try and isolate a libxml issue and - in the fortunate case where it's clearly identified - report it to their developers.

**Closed by dginev** 2023-08-10 20:20 UTC
Labels: wontfix, postprocessing, regression
