### ISSUE TITLE
title attribute on links does not honor cleveref types

### ISSUE THREAD

**Issue by rzach** [brucemiller/LaTeXML#2169] opened 2023-07-26 17:07 UTC
This is extremely minor but since I noticed it I figured I'd report it: If you change the type of an item and make a link using `cleveref`, the `title` attribute (tooltip) does not reflect the change:
```
\documentclass{book}
\usepackage{latexml}
\usepackage{hyperref}
\usepackage{cleveref}
\crefname{enumi}{sentence}{sentences}
\begin{document}
\begin{enumerate}
  \item \label{one} Item
\end{enumerate}
Test: \cref{one}
\end{document}
```
results in
```
<a href="#Ch0.S0.I1.i1" title="item 1" class="ltx_ref"
```
but should result in
```
<a href="#Ch0.S0.I1.i1" title="sentence 1" class="ltx_ref"
```

**Comment by brucemiller** [comment] 2023-08-25 13:28
Interesting point; To the extent that `cref` type names are defined for an object, and to the extent that the title attribute (generated in postprocessing) wants to use a type name, I'm thinking the title should use any `cref` names available, whether or not the link was specifically one of the `cref` link commands.

OTOH, in light of #2162, I'm wondering what the title attribute for a link like the reported one should be.  The suggested one is exactly a duplicate of the link's content. So I'm guessing that in this case it would be best to omit the title completely, right?

**Closed** 2023-09-01 00:11 UTC
Labels: bug, packages, minor
