### ISSUE TITLE
timeout: mdframed

### ISSUE THREAD

**Issue by nschloe** [brucemiller/LaTeXML#2089] opened 2023-04-27 06:52 UTC
Running
```
latexml a.tex
```

on

```latex
\documentclass{article}

\usepackage{mdframed}

\begin{document}
\end{document}
```

runs forever on my machine. (Ubuntu 23.04, TeXLive)

**Comment by dginev** [comment] 2023-04-27 10:00
I suspect this is a duplicate of #1483 - we just don't have support for mdframed.sty yet.

It is also a commonly requested ar5iv package.

**Closed by dginev** 2023-04-27 10:00 UTC
Labels: duplicate
