### ISSUE TITLE
XMRef and postprocessing

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#732] opened 2016-04-14 12:31 UTC
In #730 we are really trying to make references inside OpenMath expressions. And the reason we were looking at the OMATTRs is that we are using something like `\text{\href{foo}{}}`. But this is not actually what we should be using. We should just make an `ltx:XMRef` and hope that this is converted into a `m:share` or `om:OMR` by postprocessing. After all, there has to be a way to make the latter two in LaTeXML. But there are three problems. 
- `ltx:XMRef` only allows an `idref` attribute of type `IDREF`, but `m:share` and `om:OMR` have `xref` and `href` attributes that are of type `anyURI`. So there is a mismatch here. 
- at least in the OpenMath postprocessor XMRef does not seem be to treated all
- there is some code in the MathML postprocessor, but I am skeptical that `ltx:XMRef` is converted to `m:share`. 
  I am not sure, but it seems to me that `ltx:XMRef` is only used for internal referencing in `ltx:XMDual` and never intended for `om:OMR` and `m:share`. Then we would need a new referencing/sharing element `ltx:XMShare` and trivial conversions. If that was not the case and `ltx:XMRef` is for Math-level sharing, then we should upgrade its `idref` attribute to an `xref` attribute with value `anyURI` and at least extend `OpenMahth.pm`. We should probably also integrate/synchronize with `\LXMid` and `\LXMRef`. 

@dginev @angerhang @brucemiller, I am looking forward to feedback.

**Comment by brucemiller** [comment] 2016-05-31 17:41
Originally, that's exactly what XMRef was designed for! But then parallel markup stole it. It certainly could be *re*adapted to support ```m:share```; the ```IDREF``` isn't a problem, as id, idref linkage is exactly how things are connected within LaTeXML (other than labels). These get replaced by URL's later on in processing.

The question is of the *intent* of the ```XMRef```: Currently, it's used to share objects between the presentation and content branches of an ```XMDual```. Thus, whenever you're producing presentation (respectively content, be it cmml or om), upon encountering the ```XMRef```, you'll *always* want to simply follow the link to find the object to be converted. The generated presentation will always be different than the generated content, *but* you want to connect them (xref). So, basically you seldom see ```XMRef``` explicitly mentioned in the math converters, it's hidden by the calls to ```realize``` which finds the corresponding "real" node.

To recover the shared behaviour, I believe you'd at least need to record an attribute distinguishing the *intent*, and then figure out exactly under what circumstances ```realize``` should or should not follow the link (it's not intuitively obvious that the answer is obvious!).  Then it'd be a simple matter of defining the appropriate converters for the remaining ```XMRef```.  All the cross-referencing code would probably need to be looked at, as well, to see if they need to treat the intents differently.

**Comment by dginev** [comment] 2016-05-31 17:55
I have a quick HackerNews-type of reply here. Can we keep the setup here as simple as possible?

I already worry that cross-referencing is so complex that only Bruce will ever be able to understand it fully, so if a tiny part of it (XMRef) needs revisiting, maybe it's an opportunity to find clever ways to simplify the infrastructure?

**Comment by brucemiller** [comment] 2016-05-31 18:04
On 05/31/2016 01:55 PM, Deyan Ginev wrote:
> I already worry that cross-referencing is so complex that only Bruce
> will ever be able to understand it fully, so if a tiny part of it
> (XMRef) needs revisiting, maybe it's an opportunity to find clever ways
> to simplify the infrastructure?

Having written a paper about the cross-referencing that, while not
particularly deep, I'm not sure I even understand it...

Can I play devil's advocate and ask: What, concretely, is this "simplify"
thing, to which you refer?

**Comment by brucemiller** [comment] 2016-05-31 18:11
Less tongue in cheek: The cross-referencing stuff is, I think, inherently
complex, though no doubt it could be (gradually) cleaned up & clarified.

But I also think that the two notions *may* be coupled, so
that creating a *separate* share element would make it more rather than
less complex.  For example, if you're generating pmml, and hit an 
sharing-XMRef:
should you follow it and generate a "complete" pmml expression,
or should it be some kind of link?

In the former case, realizing nodes would need to know about both forms
of XMRef; but in the latter, it might be fine to have separate ones.

**Comment by dginev** [comment] 2016-05-31 18:13
For instance, keep the horizontal and vertical referencing conceptually separated. Reusing XMRef makes sense if there is a LOT of common infrastructure that comes into play with the current use for duals. But if that is not the case, as I suspect, and the Content MathML share is a largely orthogonal issue to implement, it may be a better move to use a new element and keep XMRef out of it.

Thinking of then later cross-referencing a content share with a presentational counterpart makes my brain hurt. I am looking at the example here: https://www.w3.org/TR/MathML3/chapter4.html#contm.share

Also adding to this confusion is that "presentational" references (e.g. thinks produced by \href) have little to do with content references / sharing, and are in fact *not* appropriate as m:share.

All of this is too complicated which threatens to make it unusable. My instinct is to support and document the basic meaningful use cases here, and be highly suspicious of any ultra-advanced ones.

**Comment by dginev** [comment] 2016-05-31 18:16
> For example, if you're generating pmml, and hit an
sharing-XMRef:
should you follow it and generate a "complete" pmml expression,
or should it be some kind of link?

Well that is not a question to latexml, but a question to the authoring language. LaTeXML should create presentation mathml as intended by the LaTeX author. LaTeX does not currently have any support for such fancy sharing-XMRef constructs, and sTeX is trying to invent them now, from what I understand.

My please to keep this as simple as possible, and then simpler, also holds for the sTeX side of the endeavor.

**Comment by brucemiller** [comment] 2016-05-31 19:12
Oh, but it exactly *is* a question that LaTeXML has to tackle if you've got both kinds of REF's (whether on the same element or not).

So, Michael is going to type ```\Share{foo}``` in the middle of some math, right? That's going to end up in the token stream, parsed into an expression tree and eventually converted into something.  Unless you forgo conversion to pmml, then you're going to have to address the question: What do I do with ```<whatever-Share-produced/>```?  What *does* the author want? I dunno.

Some claim that Eihstein said: Simplify as much as possible, but no more.  But perhaps it was Ockham or Sherlock Holmes; who knows. Even more so: Don't simplify until you know what you're trying to do.

**Comment by dginev** [comment] 2016-05-31 19:30
You've made my point for me. The meaning of ```\Share``` is provided by the package defining it, not by LaTeXML. 

We are talking about sharing in math expressions, which can be:
  -  vertical (between representations) or
  -  horizontal (between subexpressions in the same representation)


We have a power set of 2 of possible use cases:

- no sharing - the default when cross-referencing is disabled and writing regular latex
-  vertical sharing, aka "cross-referencing" - regular latex with default pmml+cmml output
- horizontal sharing - a ```\Share```-like macro in sTeX, without cross-referencing enabled
- vertical+horizontal - a ```\Share```-like macro with cross-referencing enabled

Since the share element is in content mathml, the binding author should specify the expected presentation behavior here. As you've mentioned, it can be either 
 - insert a copy of the subtree at the presentation pass
 - insert a reference to the subtree (a-la \href) at the presentation pass.

But this distinction is a bit of a falsehood in the simplest, basic use, as the expected presentation would always be to see the exact copy of the shared subtree, and never any alias or mock placeholder. If the need is for the latter, there should be a special macro, with a special binding definition, that writes out an XMDual that constructs that.

So, from my simplicity perspective:
 - horizontal sharing doesn't exist in standard latex, so by default there is no expectation of latexml to support it
 - if we enable horizontal sharing, the expected presentation in classical math/latex should be the canonical behaviour
 - if an advanced package needs to scaffold a more elaborate presentational behavior, it can do so using XMDuals.

And if that isn't controversial, then the actual implementation should make it very straightforward to distinguish between the "horizontal" and "vertical" sharing markup, and construction logic.

Also, I would like to counter:
> Don't simplify until you know what you're trying to do.

with
> Don't paint yoruself into a corner that requires massive refactoring

**Comment by brucemiller** [comment] 2016-05-31 20:45
I think there are several misunderstandings lurking here
(on one side or the other), so I'll use long-quoting form.

On 05/31/2016 03:30 PM, Deyan Ginev wrote:
> You've made my point for me. The meaning of |\Share| is provided by the
> package defining it, not by LaTeXML.

But we're being asked to provide *support* for the range
of expected behaviors, right?

> We are talking about sharing in math expressions, which can be:
>
>   * vertical (between representations) or
>   * horizontal (between subexpressions in the same representation)

Not quite the axes I'd use, but OK.

> We have a power set of 2 of possible use cases:
>
>   * no sharing - the default when cross-referencing is disabled and
>     writing regular latex
>   * vertical sharing, aka "cross-referencing" - regular latex with
>     default pmml+cmml output
>   * horizontal sharing - a |\Share|-like macro in sTeX, without
>     cross-referencing enabled
>   * vertical+horizontal - a |\Share|-like macro with cross-referencing
>     enabled

Nope, a false quadcotomy (?).  XMDual and XMRef are
nowadays *very* heavily used within LaTeXML, whether or not
the user ultimately wants pmml, cmml, parallel cross-referenced or not.
Although it wasn't easy to introduce, and there still needs to be
some nicer idioms factored out for managing it, it has *greatly* 
simplified (!)
a lot of code by virtue of giving flexibility to deal with a multitude
of random "looks like this" but "means that" constructs.  Almost all
semantic math macros, or macros with arguments, or stuff with weird spacing,
etc, end up as XMDuals. Recall the early incarnation of XMath had an
ever growing number of weird attributes to try to paste it all together,
as folks were asking for color, correct spacing, etc.

So, completely forget cross-referencing and parallel markup (other
than XMath's!) for the moment.  The questions are how to generate
presentation and how to generate content (cmml or om).

> Since the share element is in content mathml, the binding author should

Content MathML is irrelevant here: The issue is how to represent, and 
process
it within XMath on the way to (possibly) becoming Content MathML.
The "new" Share XMath element is similar to XMRef, but may --- or may 
NOT ---
behave differently. That's what we need to determine.

> specify the expected presentation behavior here. As you've mentioned, it
> can be either
>
>   * insert a copy of the subtree at the presentation pass
>   * insert a reference to the subtree (a-la \href) at the presentation pass.
>
> But this distinction is a bit of a falsehood in the simplest, basic use,
> as the expected presentation would always be to see the exact copy of
> the shared subtree, and never any alias or mock placeholder. If the need
> is for the latter, there should be a special macro, with a special
> binding definition, that writes out an XMDual that constructs that.

I think you've got XMDual backwards. Your "unexpected" behavior
would be the easy one to accomplish: Simply create a new element
(say XMShare) with an idref; It maps to m:share in cMML, and a+href in pMML.

Your expected behavior is exactly the one that introduces the complication;
not the other way around.  Your saying that (by default) when producing
pMML and encountering a Share element, we should *follow* the link.
However, when producing cMML (or OM), we should insert a m:share.
You could try to accomplish that with an XMDual, by finding the presentation
tree for the linked expression and store that in the presentation branch
of the XMDual, but you'd still need XMShare (or a variant XMRef) for
the content side.

> So, from my simplicity perspective:
>
>   * horizontal sharing doesn't exist in standard latex, so by default
>     there is no expectation of latexml to support it

Completely wrong implication!
Unless, of course, in the meantime you've given up on either spacing, 
color, etc
on the one hand, or the eventual content MathML on the other! :>

>   * if we enable horizontal sharing, the expected presentation in
>     classical math/latex should be the canonical behaviour

It's always enabled and occurring, but yes: the goal is that
it should behave as "usual".

>   * if an advanced package needs to scaffold a more elaborate
>     presentational behavior, it can do so using XMDuals.
>
> And if that isn't controversial, then the actual implementation should
> make it very straightforward to distinguish between the "horizontal" and
> "vertical" sharing markup, and construction logic.

It's only uncontroversial to the extent one is clear that
you have to be able to represent the desired data in
both the content & presentation branches of an XMDual.

> Also, I would like to counter:
>
>     Don't simplify until you know what you're trying to do.
>
> with
>
>     Don't paint yoruself into a corner that requires massive refactoring

If the corner to which you refer is XMDual/XMRef, that train's
already sailed! :>
My point is that I'm not going to do any painting at all until
I know what the surface is.

**Comment by dginev** [comment] 2016-05-31 21:09
On 05/31/2016 04:45 PM, bruce miller wrote:
> I think there are several misunderstandings lurking here
> (on one side or the other), so I'll use long-quoting form.

Will do the same (email replying is cool!)

> 
> On 05/31/2016 03:30 PM, Deyan Ginev wrote:
>> You've made my point for me. The meaning of |\Share| is provided by the
>> package defining it, not by LaTeXML.
> 
> But we're being asked to provide *support* for the range
> of expected behaviors, right?
> 

I think as it stands we're rather asked to co-invent the range of
expected behaviours :>

>> We are talking about sharing in math expressions, which can be:
>>
>>   * vertical (between representations) or
>>   * horizontal (between subexpressions in the same representation)
> 
> Not quite the axes I'd use, but OK.
> 
>> We have a power set of 2 of possible use cases:
>>
>>   * no sharing - the default when cross-referencing is disabled and
>>     writing regular latex
>>   * vertical sharing, aka "cross-referencing" - regular latex with
>>     default pmml+cmml output
>>   * horizontal sharing - a |\Share|-like macro in sTeX, without
>>     cross-referencing enabled
>>   * vertical+horizontal - a |\Share|-like macro with cross-referencing
>>     enabled
> 
> Nope, a false quadcotomy (?). 

My perspective is certainly different, but I'm happy to defend it from
being called "false". Note that I wrote "use cases". This is a valid
matrix of 4 ways in which latexml can be *used* to produce any of the
enumerated representations. I was not talking about internals here.

> XMDual and XMRef are
> nowadays *very* heavily used within LaTeXML, whether or not
> the user ultimately wants pmml, cmml, parallel cross-referenced or not.
> Although it wasn't easy to introduce, and there still needs to be
> some nicer idioms factored out for managing it, it has *greatly* 
> simplified (!)
> a lot of code by virtue of giving flexibility to deal with a multitude
> of random "looks like this" but "means that" constructs.  Almost all
> semantic math macros, or macros with arguments, or stuff with weird spacing,
> etc, end up as XMDuals. Recall the early incarnation of XMath had an
> ever growing number of weird attributes to try to paste it all together,
> as folks were asking for color, correct spacing, etc.

Sure, happy to agree with all of that.

> 
> So, completely forget cross-referencing and parallel markup (other
> than XMath's!) for the moment.  The questions are how to generate
> presentation and how to generate content (cmml or om).
> 

I'd rather not forget the reason we're doing something while designing
the solution :>

>> Since the share element is in content mathml, the binding author should
> 
> Content MathML is irrelevant here: The issue is how to represent, and 
> process
> it within XMath on the way to (possibly) becoming Content MathML.
> The "new" Share XMath element is similar to XMRef, but may --- or may 
> NOT ---
> behave differently. That's what we need to determine.
> 

Agreed, if we agree about there being valid use cases for each
combination of horizontal and vertical referencing, we can agree that we
should think of them separately, and find a simple implementation that
makes each+both possible in XMath. That does not contradict what I
wrote, rather it follows from it.

>> specify the expected presentation behavior here. As you've mentioned, it
>> can be either
>>
>>   * insert a copy of the subtree at the presentation pass
>>   * insert a reference to the subtree (a-la \href) at the presentation pass.
>>
>> But this distinction is a bit of a falsehood in the simplest, basic use,
>> as the expected presentation would always be to see the exact copy of
>> the shared subtree, and never any alias or mock placeholder. If the need
>> is for the latter, there should be a special macro, with a special
>> binding definition, that writes out an XMDual that constructs that.
> 
> I think you've got XMDual backwards. Your "unexpected" behavior
> would be the easy one to accomplish: Simply create a new element
> (say XMShare) with an idref; It maps to m:share in cMML, and a+href in pMML.
> 
> Your expected behavior is exactly the one that introduces the complication;
> not the other way around.  Your saying that (by default) when producing
> pMML and encountering a Share element, we should *follow* the link.
> However, when producing cMML (or OM), we should insert a m:share.
> You could try to accomplish that with an XMDual, by finding the presentation
> tree for the linked expression and store that in the presentation branch
> of the XMDual, but you'd still need XMShare (or a variant XMRef) for
> the content side.

Again, I approached this from the "use case", not from the internals.
There was no claim that one scenario was "easier" than the other, but
that there would be an intuitive behaviour expected from a classic
math/latex perspective. Apples and oranges.

I actually don't have strong opinions on how to implement yet, but a
simple solution ought to be more elegant?

> 
>> So, from my simplicity perspective:
>>
>>   * horizontal sharing doesn't exist in standard latex, so by default
>>     there is no expectation of latexml to support it
> 
> Completely wrong implication!
> Unless, of course, in the meantime you've given up on either spacing, 
> color, etc
> on the one hand, or the eventual content MathML on the other! :>
> 

Erm, who's misunderstanding who here? Classic latex includes and implies
all of spacing, color, font information, etc. It does not imply content
mathml directly, and we've had this discussion before about it being one
of the most "experimental" features of LaTeXML. In many ways I continue
to see the content mathml capacity as something closer to LLaMaPun than
to LaTeXML. So yes, having the horizontal references is just as an
"extra" feature as the content mathml generation is. Still great to have
both, but not part of the "core" feature set for a latex to html
conversion service (the way I see that).

>>     Don't paint yoruself into a corner that requires massive refactoring
> 
> If the corner to which you refer is XMDual/XMRef, that train's
> already sailed! :>

Sure, all I said is that it's good to keep an eye out for simplicity, my
remark was intended to be as vague as it sounds.

> My point is that I'm not going to do any painting at all until
> I know what the surface is.
> 

That also sounds great to me.

**Comment by kohlhase** [comment] 2016-06-01 04:50
I am not sure that I am getting all the stuff you are discussing here, but let me state my use case(s).

First the basic use case (less basic ones in other comments)
 
I want to be able to say (making up macros ```\mark``` and ```\share``` for the argument)
```
\mark{a}{x-y}+\share{a}^2
```
Which generates 
```
<semantcis> 
   <mrow>
      <mrow id="first"><mi>x</mi><mo>+</mo><mi>y</mi></mrow>
     <mo+<mo> 
     <msup>
         <mrow id="second"><mi>x</mi><mo>+</mo><mi>y</mi></mrow>
        <mn>2</mn>
     <msup>
   </mrow>
   <annotation-xml encoding="content MathML"> 
     <appply>
       <plus/>
       <apply id="a" xref="first"><minus><ci>x</ci></ci>y</ci></appy>
      <share href="x" xref="second"/>
    </apply>
  </annotation-xml>
</semantics>
```
Note that the presentation does not have a ```share```, but the content does. Now the crossreferencing, that is relatively simple, since the crossrefs go from content to the first. 
There is currently no way of producing that in LaTeXML that I am aware of.

**Comment by kohlhase** [comment] 2016-06-01 04:57
The basic use case is what @dginev calls "vertical" I think. Horizontal sharing is just as natural: 
```
Let $\theta$ be $\mark{a}{x-y}$, then $\theta^2$ is $\share{a}^2$. 
```
to stay near the example above. I want this to generate 
```
<p>
 Let $\theta$ be 
<math>
  <semantcis> 
     <mrow>
     <mi>\theta</mi><mo>=</mo> 
      <mrow id="first"><mi>x</mi><mo>+</mo><mi>y</mi></mrow>
   </mrow>
   <annotation-xml encoding="content MathML"> 
     <appply>
       <eq/>
       <apply id="a" xref="first"><minus><ci>x</ci></ci>y</ci></appy>
    </apply>
  </annotation-xml>
</semantics>
</math>
then $\theta^1$ is 
<semantcis> 
     <msup>
         <mrow id="second"><mi>x</mi><mo>+</mo><mi>y</mi></mrow>
        <mn>2</mn>
     <msup>
   <annotation-xml encoding="content MathML"> 
    <apply><power/><share href="x" xref="second"/><cn>2</cn></apply>
  </annotation-xml>
</semantics>

**Comment by kohlhase** [comment] 2016-06-01 04:59
Note that I would also like to enable cross-file sharing. 
Also I think there is no techical difference to horizontal and vertical sharing.

**Comment by kohlhase** [comment] 2016-06-01 05:14
Oh, and even though I have thought about this a bit, I do not see any other use cases realistically. And things seems to simple and structural to me that I am not sure what the discussion is really about (correct me if I am naive again). 
It seems to me that on the presentation side if you treat ```\mark{a}{A}``` as generating  macro for referencing and processing A i.e. as ```A\def\mark@a{A}``` and ```\share{a}``` as ```\mark@a```. Then share-expansion should come early and parsing should still work (assuming that that is done after macro expansion). And on the content side, ```\mark{a}{A}``` should just generate whatever ```A``` is and decorate it with an ```id="a"``` and ```\share{a}``` should just generate ```<XMshare href="a">```. 

But I am sure that I am being too naive, I just do not see where.

**Comment by kohlhase** [comment] 2016-06-01 05:21
Oh, and I forgot to say that I am very happy to see that you are attacking this problem. Apart from my sTeX use case, I think that LaTeXML should be contentMathML complete, i.e. that we should be able to create all legitimate cMathML (possibly with the help of simple bindings).

**Comment by brucemiller** [comment] 2016-06-03 22:40
If I've understood Deyan's axis, "vertical" sharing is across representations of the same object, in otherwords the existing mechanism used by XMDual and XMRef; "horizontal" sharing is across expressions or between them, connecting arbitrary subexpressions.  Horizontal is the new capability.  Both your examples would be horizontal.

But you did answer the question about expectations: the presentation side shouldn't be exposing the share (via some sort of linking mechanism), but should just present the shared expression; only the content side would share via a link.

I'll comment on your implementation ideas separately.

**Comment by brucemiller** [comment] 2016-06-04 15:08
Let's think some more about the requested features and their impact on implementation.

Your suggestion of using macros is very LaTeXy; presumably storing shared expressions in an .aux file (which we've managed to avoid in LaTeXML, so far).  It solves a parsing issue in knowing how the shared expression fits within its new home.  But it actually is *too* flexible!

The target mechanism only supports sharing single "proper", or complete, subexpressions; the macro approach would allow you to share ```\mark{foo}{^x}```, for example and have ```\X\share{foo}``` properly parsed as ```X^x```, but foo would no-longer exist as a tree within the cmml!

Actually, the current parsing system deals quite well with proper subexpressions (up to a point): it parses sub/superscripts, numerators,denomnators, etc, separately, as long as it can treat them as fairly generic "atomic" expressions at the layer above. That might be the rub here. You presumably wouldn't want to share a ```^x```, like above, but you *might* want to share, say, an operator?  The parser would need to know that in ```\share{someop} X``` the shared expression is being applied to X (in some fashion) rather than perhaps implicitly multiplied. That's the only situation where I see an advantage to an "early" sharing: to know the syntactic role of an expression.

**Comment by brucemiller** [comment] 2016-06-04 15:14
I should add, a conceivable solution to needing the role might be ```\share[OPERATOR]{someop}```; obviously not the most elegant, but perhaps could be turned into a Feature :>

**Comment by kohlhase** [comment] 2016-06-05 09:02
> the presentation side shouldn't be exposing the share (via some sort of linking mechanism), but should just present the shared expression; only the content side would share via a link.

indeed, that is exactly what I mean. For MathML3, we agreed that "sharing" on the presentation side does not really make sense (and I agree with this).

**Comment by kohlhase** [comment] 2016-06-05 09:40
> The target mechanism only supports sharing single "proper", or complete, subexpressions; the macro approach would allow you

I like your example. I agree, Indeed I  would not want to share ```^x```. BTW, as sTeX expressions are more "semantic", and therefore this would appear. 

Maybe the solution here is that LaTeXML should have an XMShare element that is the counterpart of <OMR>  and <share> elements in OpenMath and MathML, but should not provide ```\mark``` and ```\share``` macros. These are then left to the extensions like sTeX, where they are less harmful (as pointed out above).

**Comment by brucemiller** [comment] 2016-06-05 12:04
> Maybe the solution here is that LaTeXML should have an XMShare element
> that is the counterpart of and elements in OpenMath and MathML, but
> should not provide |\mark| and |\share| macros. These are then left to
> the extensions like sTeX, where they are less harmful (as pointed out
> above).

But leaving off the macros doesn't buy anything, unless
the infrastructure is there to either process or represent them.

**Comment by dginev** [comment] 2016-06-05 13:47
For the record, burdening the authoring language with new macros to annotate content shares is (one more) hit on usability. I personally would be rather conservative in that regard (the macro density in writing sTeX is already really high), and instead look for ways to auto-generate the shares.

Given how well annotated the typical sTeX formula is, one or several well-targeted DefMathRewrites in the sTeX bindings may do the job without the need of extra macros.

**Comment by brucemiller** [comment] 2016-06-05 14:01
On 06/05/2016 09:47 AM, Deyan Ginev wrote:
> For the record, burdening the authoring language with new macros to
> annotate content shares is (one more) hit on usability. I personally
> would be rather conservative in that regard (the macro density in
> writing sTeX is already really high), and instead look for ways to
> auto-generate the shares.
>
> Given how well annotated the typical sTeX formula is, one or several
> well-targeted DefMathRewrites in the sTeX bindings may do the job
> without the need of extra macros.

Given that I don't know sTeX's approach: If the intent of the existing
sTeX markup makes clear when a shared object is being made, and when a
reference to a shared object is being made, then of course there's no
need to expose that to the document author.

But whether done by macros or something else, the infrastructure needs
to be there.

**Comment by dginev** [comment] 2016-06-05 14:11
> But whether done by macros or something else, the infrastructure needs
to be there.

We're in full agreement there. I am still wondering what the use case of using share is for sTeX (saving space?), but since it's legitimate content MathML having infrastructure for it can't be that bad.

**Comment by kohlhase** [comment] 2016-06-05 14:13
saving space is one thing. But also saving typing :-). and sharing makes maintenance simpler.

**Comment by dginev** [comment] 2016-06-05 14:22
Well latex macros already allow to save typing, I was only wondering of the new representational construct.

**Comment by kohlhase** [comment] 2016-06-05 14:34
In content MathML and OpenMath we can represent expressions considerably more efficiently using sharing. For machine-generated content e.g. proof objects with inner types, the factor is often over 1000.

**Comment by dginev** [comment] 2016-06-05 15:25
Since Bruce seems to be quite interested here, I'll defer to him, but I'll restate my opinion after the discussion. From what I have seen from the comments here:

 * the content "share" element as such is only needed to conserve space
 * the main sTeX issue that spawned this spin-off issue relates to actual natural-language references, represented as math objects, which is a completely separate discussion topic.
 * LaTeXML's existing infrastructure should allow for writing such bindings already, possibly via a clever use of XMDual, or via sTeX's notation mechanism.
 * At the same time the idea of representing NL references as math objects is advanced enough to be sTeX-specific, and remain out of scope for the core LaTeXML bindings.
 * I suspect there may be need of entirely new content symbols + dictionaries to capture the "referencing" behaviour. Referencing isn't sharing, it gets complicated quickly. But sTeX's notation mechanism should be sufficiently open-ended to capture that.

Just my two cents here. In brief, I can't figure out if the extra layer of infrastructure we're brainstorming here is worth adding, given we have no compelling use case for it.

**Comment by brucemiller** [comment] 2016-06-05 19:31
Interested, to a point, but not that convinced that compactness is that important, given the complications of follow-on applications to have to track references.  Seems like a use for Abstraction :>.  Also, I don't find being able to express all possible MathML features as a compelling goal. Nevertheless, I'm not (yet) against the idea.

LaTeXML currently has no way to generate an ```m:share``` element in the output, so games w/ XMDual or sTeX alone aren't going to help.

I don't understand @dginev's last bullet about referencing, but it seems that the intention from the MathML spec is that share has no implied semantics and is equivalent to having substituted the shared object.

**Comment by brucemiller** [comment] 2016-06-05 19:41
So, given the "requirements" (or wishes), I'll say again: The XMRef element does most of what you need already.  Currently, when generating both presentation & content, an XMRef is followed, effectively replacing it by the referenced object.  What you want is a *special* XMRef that does *not* get replaced when generating content (but does in presentation, as before).  In that case, the XMRef that remains should be converted to an m:share.  Pretty simple, really.

Modulo:
 * random corner cases of "Didn't expect an XMRef *here*!!!". 
 * cross-referenced parallel markup would have to be tested: Might work as is, might not.
 * sharing across files would be a mess, unless you store them in the ObjectDB (doable)
 * for shares outside the current file, treating the shared object as anything other than ATOM would also be a mess.

**Comment by dginev** [comment] 2021-08-09 22:28
Judging by the last 5 years, my comment back in 2016:
>  Just my two cents here. In brief, I can't figure out if the extra layer of infrastructure we're brainstorming here is worth adding, given we have no compelling use case for it.

seems to have answered itself.

**Closed by dginev** 2021-08-09 22:28 UTC
Labels: enhancement, postprocessing, schema
