### ISSUE TITLE
Glossary test fail during make test

### ISSUE THREAD

**Issue by goska** [brucemiller/LaTeXML#1474] opened 2021-03-01 14:09 UTC
Thank you for releasing LaTeXML 0.8.5!
During installation on Mac today I got the following test fail reported by make test: 
```
#   Failed test 't/structure/glossary'
# Difference at line 43 for t/structure/glossary
#       got : '    <p>First use: <glossaryref key="svm">support vector machine (SVM)</glossaryref>. Second use: <glossaryref key="svm">SVM</glossaryref>. A use <glossaryref key="svm">SVM</glossaryref>within a sentence.</p>'
#  expected : '    <p>First use: <glossaryref key="svm">support vector machine (SVM)</glossaryref>. Second use: <glossaryref key="svm">SVM</glossaryref>. A use <glossaryref key="svm">SVM</glossaryref> within a sentence.</p>' 
```
The test reports a missing space after ">" in "</glossaryref>within".
I have used an installation from source with LaTeXML 0.8.5 files downloaded from LaTeXML website https://dlmf.nist.gov/LaTeXML/releases/LaTeXML-0.8.5.tar.gz

**Comment by dginev** [comment] 2021-03-01 14:31
Hm, it's a single space difference before "within". Interesting why that would be different on a Mac compared to our mainline tests - could you share the version of your texlive installation as well?

**Comment by goska** [comment] 2021-03-01 17:20
I'll check and do. Neither the OS nor  Texlive installed on my Mac are very recent - perhaps that could be the reason.

**Comment by goska** [comment] 2021-03-02 10:50
Texlive version is Texlive 2015. Perl: 5.26. Still running macOS High Sierra (using old MacBook; I am unable to access my work machine due to the lockdown.)

**Comment by brucemiller** [comment] 2021-03-02 23:31
Curious; works w/TeXlive 2015 on my system (using devel version of LaTeXML); the test is supposed to be disabled for TeXlive 2014.

Which turned up an interesting side bug: you can select which `kpsewhich` (and thus, which texmf directory) using the `LATEXML_KPSEWHICH` environment variable. However, `LaTeXML::Util::Test` uses the version from the `tex` command to determine which TeX installation is present, and thus which tests to exclude. Thus, if you use the env var, it's excluding the wrong tests.  Unfortunately, `kpsewhich` doesn't include the TeXlive version in it's `--version` output. Sigh...

**Comment by brucemiller** [comment] 2021-07-30 13:04
Is this issue still an issue?  All tests are working correctly on my system on a variety of TeXlive versions.

**Comment by dginev** [comment] 2021-07-30 13:10
@brucemiller you tried 2015?

**Comment by dginev** [comment] 2021-07-30 13:12
How about we also disable the test on 2015, just in case some other installations like the one reported end up failing to install on that texlive? 

I don't think a problem there should prevent installation entirely, also since the error is just a whitespace mismatch, and the texlive version is quite outdated.

**Comment by brucemiller** [comment] 2021-07-30 15:18
Yep, 2015 was included.
I'd just as soon close it as is, since
2015 is old and rare anyway, and a peculiar version of it rarer yet.

**Comment by dginev** [comment] 2021-07-30 15:26
Well, apologies to @goska , and I hope a new texlive will soon become available on her end!

**Comment by dginev** [comment] 2021-07-30 16:08
And just after I conceded to resolve, I get a reproducible run that can induce the error, which really makes me thing we should resolve one way or another, instead of closing. Tom's docker run, for Bruce to co-inspect:

https://github.com/tkw1536/LaTeXML/runs/3203588747?check_suite_focus=true

I think we should reopen and either drop the test for 2015, or fix the minor issue causing the whitespace diff.

**Comment by brucemiller** [comment] 2021-07-30 16:14
Hmm....
Where the heck did Tom get that nasty 2015? :>

Last time I wrestled with this kind of bug, it was sorta tricky about 
where spaces get skipped or not. But I'd go along with either solution:
If you can fix it, fine; otherwise just disable the test for old TeXLives.

**Comment by tkw1536** [comment] 2021-07-30 16:38
As for where I got 2015: I simply reused the versions that were already enabled. We can turn it off completely if you like.

**Closed** 2021-08-06 04:44 UTC
Labels: wontfix, installation, regression
