### ISSUE TITLE
various bibtex-related problems

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#981] opened 2018-05-01 06:03 UTC
I am using ```bibtest.tex```
```
\documentclass{article}
\usepackage{url}
\begin{document}
\cite{Ginev-11,}
\bibliographystyle{alpha}
\bibliography{test}
\end{document}
```
with ```test.bib```
```
@MastersThesis{Ginev-11,
  author =   {Deyan Ginev},
  title =    {The Structure of Mathematical Expressions},
  school =   {Jacobs University Bremen},
  address =  {Bremen, Germany},
  type =     {Master's Thesis},
  month =    aug,
  url = {http://kwarc.info/people/dginev/publications/DeyanGinev_Mastersthesis.pdf},
  howpublished = {\url{http://kwarc.info/people/dginev/publications/DeyanGinev_MScThesis.pdf}},
  pubs = {dginev,omdoc,openmath},
  keywords = {lamapunbibs,mscthesis},
  year =     {2011}}
```
and get 
```
MiKo:tmp kohlhase$ latexmlc --destination bibtest.html bibtest

(Loading /Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/TeX.pool.ltxml...
(Loading /Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/eTeX.pool.ltxml... 0.00 sec)
(Loading /Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/pdfTeX.pool.ltxml... 0.00 sec) 0.11 sec)

latexmlc (LaTeXML version 0.8.2; revision 38fc034e)
processing started Tue May  1 07:57:50 2018

(Digesting TeX bibtest...
(Processing content /Users/kohlhase/tmp/bibtest.tex...
(Loading /Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/LaTeX.pool.ltxml... 0.11 sec)
(Loading /Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/article.cls.ltxml... 0.01 sec)
(Loading /Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/url.sty.ltxml... 0.00 sec) 1.32 sec) 1.33 sec)
(Building...
(Loading compiled schema /Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.01 sec). 0.04 sec)
(Rewriting... 0.00 sec)
(Finalizing... 0.00 sec)
Conversion complete: No obvious problems.

(post-processing...
(Scan bibtest.html processing... 0.00 sec)
(MakeBibliography bibtest.html processing... [Converting bibliography /Users/kohlhase/vc/git/github.com/KWARC/bibs/test.bib ...
(Digesting BibTeX test...
(Processing content /Users/kohlhase/vc/git/github.com/KWARC/bibs/test.bib... 0.00 sec)
(Preparsing Bibliography test... 0.00 sec)
(Processing content Literal String \begin{bib...
Error:undefined:\url The token T_CS[\url] is not defined.
	at Literal String \begin{bib; line 2 col 29
	Defining it now as <ltx:ERROR/>
	In Core::Stomach[@0x7fbca2a84438] at Literal String \begin{bib; line 2 col 29
	 <= Core::Definition::Constructor[\bib@@f... <= Core::Stomach[@0x7fbca2a84438] <= Core::Definition::Constructor[\begin{... <= ...

Error:unexpected:_ Script _ can only appear in math mode
	at Literal String \begin{bib; line 2 col 29
	In Core::Definition::Primitive[Subscript] from TeX.pool.ltxml line 3727
	 <= Core::Stomach[@0x7fbca2a84438] <= Core::Definition::Primitive[Begin] <= Core::Stomach[@0x7fbca2a84438] <= ...
 0.03 sec) 0.03 sec)
(Building...
(Loading compiled schema /Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.01 sec). 0.04 sec)
(Rewriting... 0.00 sec)
(Finalizing... 0.00 sec)
... converted!] [using bibliographies test.bib] [1 bibentries, 1 cited] 0.47 sec)
(CrossRef bibtest.html processing...
Info:expected:ids Missing items:
	  Usable title for ID: p1
 0.00 sec)
(XSLT[using LaTeXML-html5.xsl] bibtest.html processing... 0.00 sec)
(Writer bibtest.html processing... 0.00 sec) 0.47 sec)
Post-processing complete: 2 errors; 1 undefined macro[\url]
processing finished Tue May  1 07:57:52 2018
Status:conversion:2 
No obvious problems
2 errors; 1 undefined macro[\url]
Wrote bibtest.html
```
As you can see there are quite a few things wrong: 
- `\url` is undefined
- the line numnbers in the error messages are unusable: `at Literal String \begin{bib; line 2 col 29
`
- message that seems unrelated `Info:expected:ids Missing items: Usable title for ID: p1`
- I guess the `script only in math mode` error is a follow-up from the `\url` failure

**Comment by kohlhase** [comment] 2018-05-01 06:05
Ah, I see that `ID: p1` comes from the "Cited by"  message. 
BTW, that is non-standard, and should not really be generated (or made invisible by default in the css) .

**Comment by dginev** [comment] 2018-05-01 07:38
The technical reason behind this issue is the same as for #980 , the bibliography conversion in post-processing happens in isolation from the main document, so no definitions are transferred over.

**Comment by dginev** [comment] 2018-05-25 13:22
Moving to next milestone (0.8.4), so that we roll out 0.8.3 asap. Apologies this issue didn't make the cut.

**Comment by dginev** [comment] 2019-08-07 20:27
The bug pat of the issue is now solved with the latest master, example produces:
![image](https://user-images.githubusercontent.com/348975/62655480-11d12a00-b930-11e9-99e2-9199c882b450.png)


The `Usable title for ID: p1` Info message is still generated, but only because the test file does not have any structural elements to hold the citation. If you prepend a `\section{Example}` or such, the Info disappears and the `Cited by:` is filled correctly. So I think this is finally solved!

**Closed by dginev** 2019-08-07 20:27 UTC
Labels: bibliography, bug
