### ISSUE TITLE
TikZ output distorted

### ISSUE THREAD

**Issue by flyn-org** [brucemiller/LaTeXML#1196] opened 2019-08-23 18:48 UTC
First, thank you for LaTeXML!

I find that the output generated from TikZ by LaTeXML ends up distorted.

Here is an example input:

```
\begin{tikzpicture}
        \node [draw,shape=rectangle] (server) at (0, 0) {SNPC Server $S$};
        \node [draw,fill=yellow,very thick,shape=rectangle] (worker) at (0, -2) {worker $W$};
        \node [draw,fill=yellow,very thick,shape=rectangle,text width=1.25cm,align=center] (proxy) at (-3, -2) {proxy~$P$ ($I_1$)};
        \node [draw,shape=rectangle] (dependent) at (-6, -2) {dependent $D$};

        \node at (0.3, -1.55) {$C_S$};
        \node at (-1.1, -1.8) {$C_P$};
        \node at (-1.9, -1.8) {$C_W$};
        \node at (-1.9, -2.2) {($P_1$)};
        \node at (-4, -1.8) {$C_D$};
        \node at (-4.05, -2.2) {($P_2$)};

        \draw (server) -- (worker);
        \draw[dotted] (worker) -- (proxy);
        \draw (proxy) -- (dependent);
\end{tikzpicture}
```

Here is a document containing this picture, processed by pdflatex, and rendered as it should be by evince:

![pdfviewer](https://user-images.githubusercontent.com/6109247/63616350-6540aa80-c5b5-11e9-8b90-8614c85e227e.png)

Here is the same document, processed with `latexml instructions.tex >instructions.xml` and `latexmlpost --format=html5 instructions.xml >instructions.html`, and rendered by a browser with distortions:

![browser](https://user-images.githubusercontent.com/6109247/63616398-7a1d3e00-c5b5-11e9-99f4-2b3cf11c2686.png)

Here is the entire document:

[instructions.txt](https://github.com/brucemiller/LaTeXML/files/3535800/instructions.txt)

It is not clear to me how accurate the TikZ processing in LaTeXML is expected to be. I am also not sure if this is a browser issue, although I have tried Chrome, Firefox, and GNOME Epiphany (Web).

**Comment by dginev** [comment] 2019-09-04 15:04
This example is even further regressed on the latest master and texlive 2019, so there may indeed be some need to revisit the tikz interpretation internals on our part. Here is what I am seeing for this conversion:

![image](https://user-images.githubusercontent.com/348975/64267070-bb8de180-cf03-11e9-8fea-79b79fa87e0a.png)

**Comment by dginev** [comment] 2019-09-04 15:10
Here is a Gist of the indented SVG I am getting. The first weird tidbit I noticed is that there are empty `<p class="ltx_p" />` elements inserted wrapped in foreign objects. The actual textual content is still in the XML markup, so with some luck it is a more shallow markup issue, rather than a deep interpretation problem in TeX.

https://gist.github.com/dginev/f3ebeaf96ce7682f9410483a120fa50b?short_path=39fb67b

**Comment by dginev** [comment] 2020-11-03 16:51
Quick note: the texlive 2019 regression has been resolved in the latest latexml master (my blank boxes image). The issue is still unsolved however, but the distortions are back to exactly as they were in the original issue report. Hope we can address this for 0.8.6!

**Comment by brucemiller** [comment] 2020-12-29 03:20
It looks like #1413  fixes the regressions, and mostly gets the layout of your figure right. But it still ends up a bit distorted. Mostly it's cramped because (I think) that they layout is specified in absolute numbers, but all the text/math is rendering at a larger size than TeX, so they all overlap other parts of the figure.  Of course, LaTeXML is also rather poor at calculating the sizes of text/math.  Presumably there's some font sizing somewhere that is getting overlooked?

**Comment by brucemiller** [comment] 2021-08-23 20:12
Slightly improved further by #1624, but not completely right. The basic problem is LaTeXML not yet having access to accurate font size information, so all it's sizing is a rough guestimate.  In this particular graphic, there's a combination of absolute & relative sizes and positions, so LaTeXML inevitably has things bumping into each other.

So that basically means, it's not going to be fixable in the short-term. Sorry!

**Closed** 2021-09-29 18:35 UTC
Labels: bug, packages
